/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.30
 * Generated at: 2018-07-11 01:22:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class a_005fnotice_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/D:/FinalProjecthee/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/final/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/./adminpage.jsp", Long.valueOf(1531271463861L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1531112554226L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<html> \r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t\t<title>공지사항 리스트</title>\r\n");
      out.write("\t\t<script src=\"https://code.jquery.com/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("\t\t<style>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t.di{\r\n");
      out.write("\t\t\t\twidth: 500px;\r\n");
      out.write("\t\t\t\theight: 500px;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tposition: relative;\r\n");
      out.write("\t\t\t\tmargin: 0 auto;\r\n");
      out.write("\t\t\t\ttop: 100px;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\ttable{\r\n");
      out.write("\t\t\t\tborder-top: 1px solid #444444;\r\n");
      out.write("\t\t\t\tborder-spacing: 20px;\r\n");
      out.write("\t\t\t\tborder-collapse: collapse;\r\n");
      out.write("\t\t\t\tpadding: 10 10;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t.td1,.td2,.td3,.td4,.td5,.td6{border-bottom: 1px solid black}\r\n");
      out.write("\t\t\ttd,th{\r\n");
      out.write("\t\t\t\t/*border-bottom: 1px solid black;*/\r\n");
      out.write("\t\t\t\tborder-collapse: collapse;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\tpadding: 18px;\r\n");
      out.write("\t\t\t\tfont-size:13px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("            .tab{\r\n");
      out.write("                border-top: 1px solid black;\r\n");
      out.write("                \r\n");
      out.write("            }\r\n");
      out.write("            .tr{\r\n");
      out.write("               border-bottom: 1px dashed #444444; \r\n");
      out.write("              /*  border-bottom:1px dashed #444444 !important */\r\n");
      out.write("            }\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t.th{\r\n");
      out.write("\t\t\t\t/*border-bottom: 1px dashed black;*/\r\n");
      out.write("\t\t\t}\t \r\n");
      out.write("\t\t\t \r\n");
      out.write("            button#write{\r\n");
      out.write("\t             position: absolute;\r\n");
      out.write("\t             background-color: white; \r\n");
      out.write("\t             color: black; \r\n");
      out.write("\t             border-radius: 2px; \r\n");
      out.write("\t             font-size: 15px; \r\n");
      out.write("\t             top: 20.5%; \r\n");
      out.write("\t             left: 56.2%;\r\n");
      out.write("             }\r\n");
      out.write("             \r\n");
      out.write("          \t#field{\r\n");
      out.write("\t\t\t\tdisplay: inline-block;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t$(\"#write\").click(function () {\r\n");
      out.write("\t\tlocation.href=\"a_noticeWrite\";\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\turl : \"./noticeList\",\r\n");
      out.write("\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\tsuccess : function (data) {\r\n");
      out.write("\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\tprintList(data.list);\r\n");
      out.write("\t\t\t\tif(data.list != null){\r\n");
      out.write("\t\t\t\t\tprintList(data.list);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function (error) {\r\n");
      out.write("\t\t\t\tconsole.log(error);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//받아온 리스트\r\n");
      out.write("\tfunction printList(list) {\r\n");
      out.write("\t\tconsole.log(\"리스트 어팬드 여부\");\r\n");
      out.write("\t\tvar content = \"\";\r\n");
      out.write("\t\tlist.forEach(function(item, idx) {\r\n");
      out.write("\t\t\tcontent += \"<tr class ='tr1'>\";\r\n");
      out.write("\t\t\tcontent += \"<td class ='td1'>\"+item.notice_idx+\"</td>\";\r\n");
      out.write("\t\t\tcontent += \"<td class ='td2'><a href='./a_noticeDetail?notice_idx=\"+item.notice_idx+\"'>\"+item.notice_subject+\"</a></td>\";\r\n");
      out.write("\t\t\tcontent += \"<td class ='td3'>\"+item.notice_content+\"</td>\";\r\n");
      out.write("\t\t\tcontent += \"<td class ='td4'>\"+item.admin_id+\"</td>\";\r\n");
      out.write("\t\t\tvar date = new Date(item.notice_date);\r\n");
      out.write("\t\t\tcontent += \"<td class ='td5'>\"+date.toLocaleDateString(\"ko-KR\")+\"</td>\";\r\n");
      out.write("\t\t\tcontent += \"<td class ='td6'>\"+item.bHit+\"</td>\";\r\n");
      out.write("\t\t\tcontent += \"</tr class ='tr2'>\";\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#list\").empty();\r\n");
      out.write("\t\t$(\"#list\").append(content);\r\n");
      out.write("\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/a_notice.jsp(68,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.adminId != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t");
          out.write("\r\n");
          out.write("     \r\n");
          out.write("<html>\r\n");
          out.write("<head>\r\n");
          out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
          out.write("\t<title>Insert title here</title>\r\n");
          out.write("\t<script src=\"http://code.jquery.com/jquery-3.1.0.min.js\"></script>\r\n");
          out.write("\t<style>\t\r\n");
          out.write("\r\n");
          out.write("\t\t\t.top{width:100%;height: 100px;background-color: #000;color:#fff;}\r\n");
          out.write("            .top_wrap{width:700px;height: 100px;margin:0 auto;}\r\n");
          out.write("            li{list-style: none;}\r\n");
          out.write("            *{margin:0px;padding:0px}\r\n");
          out.write("            .top_right ul li{float: left;padding-right: 10px}\r\n");
          out.write("            .top_left{float: left}\r\n");
          out.write("            .top_right{float: right}\r\n");
          out.write("            a{text-decoration:none}\r\n");
          out.write("            .top_right ul li a{color:#fff}\r\n");
          out.write("\t\r\n");
          out.write("\r\n");
          out.write("\t</style>\r\n");
          out.write("</head>\r\n");
          out.write("<body>\r\n");
          if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\r\n");
          if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\r\n");
          out.write("</body>\r\n");
          out.write("<script>\r\n");
          out.write("\r\n");
          out.write("\t\r\n");
          out.write("</script>\r\n");
          out.write("</html>");
          out.write("\r\n");
          out.write("\t\t\t<div class=\"di\">\r\n");
          out.write("\t\t\t\t<table  class=\"tab\">\r\n");
          out.write("\t\t\t\t\t<thead class=\"th\">\r\n");
          out.write("\t\t\t\t\t\t<tr class=\"tr\">\r\n");
          out.write("\t\t\t\t\t\t\t<th>번호</th>\r\n");
          out.write("\t\t\t\t\t\t\t<th>제목</th>\r\n");
          out.write("\t\t\t\t\t\t\t<th>내용</th>\r\n");
          out.write("\t\t\t\t\t\t\t<th>작성자</th>\r\n");
          out.write("\t\t\t\t\t\t\t<th>작성날짜</th>\r\n");
          out.write("\t\t\t\t\t\t\t<th>조회수</th> \r\n");
          out.write("\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t</thead>\r\n");
          out.write("\t\t\t\t\t<tbody id=\"list\">\r\n");
          out.write("\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t</tbody>\r\n");
          out.write("\t\t\t\t</table>\r\n");
          out.write("\t\t\t\t\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t\t<button id=\"write\">작성하기</button> \r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/views/./adminpage.jsp(25,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.adminId != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t <div class=\"top\">\r\n");
          out.write("               <div class=\"top_wrap\">\r\n");
          out.write("            <div class=\"top_left\">\r\n");
          out.write("                <h2 id=\"mainimg\" onclick=\"location.href='./'\"> 슈마니커</h2>\r\n");
          out.write("            </div>\r\n");
          out.write("               <div class=\"top_right\">\r\n");
          out.write("                   <ul>\r\n");
          out.write("                       <li><h5 id=\"mainimg\" onclick=\"location.href='./admin_menual'\"> 슈마니커 관리자</h5></li>\r\n");
          out.write("                    <li><a href=\"adminmem\">회원관리</a></li>\r\n");
          out.write("                       <li><a href=\"adminreply\">후기관리</a></li>\r\n");
          out.write("                       <li><a href=\"a_notice\">공지사항</a></li>\r\n");
          out.write("                       <li><a href=\"./adminlogout\">로그아웃</a></li>\r\n");
          out.write("                    </ul>\r\n");
          out.write("               </div>\r\n");
          out.write("            </div>\r\n");
          out.write("          </div>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/views/./adminpage.jsp(44,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.adminId == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t<h3>관리자만 접근 가능합니다.</h3>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }
}
