/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.30
 * Generated at: 2018-07-18 04:32:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class category_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/views/./head.jsp", Long.valueOf(1531887597461L));
    _jspx_dependants.put("jar:file:/D:/FinalProjecthee/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/final/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1531184863091L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("     \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("   <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("   <script src=\"http://code.jquery.com/jquery-3.1.0.min.js\"></script>\r\n");
      out.write("   <title>Insert title here</title>\r\n");
      out.write("   <style>\r\n");
      out.write("      #wrapper {\r\n");
      out.write("         width: 1000px;\r\n");
      out.write("         margin-left: 15%;\r\n");
      out.write("         margin-top: 1%; \r\n");
      out.write("      }\r\n");
      out.write("      #mainImg {\r\n");
      out.write("         margin-top: 1%;\r\n");
      out.write("         width: 1100px;\r\n");
      out.write("         height: 300px;\r\n");
      out.write("         border-bottom: 1px solid black;\r\n");
      out.write("         \r\n");
      out.write("      }\r\n");
      out.write("      .newImg {\r\n");
      out.write("         \r\n");
      out.write("         width: 1200px;\r\n");
      out.write("         height: 200px;\r\n");
      out.write("         \r\n");
      out.write("      }\r\n");
      out.write("      .new {\r\n");
      out.write("         \r\n");
      out.write("         float: left;\r\n");
      out.write("         width: 200px;\r\n");
      out.write("         height: 200px;\r\n");
      out.write("         border: 1px solid black;\r\n");
      out.write("         margin: 1%;\r\n");
      out.write("      }\r\n");
      out.write("      .new:hover {\r\n");
      out.write("         cursor: pointer;\r\n");
      out.write("         background-color: black;\r\n");
      out.write("      }\r\n");
      out.write("      #oper{\r\n");
      out.write("         cursor: pointer;\r\n");
      out.write("      }\r\n");
      out.write("      #oper:hover {         \r\n");
      out.write("         cursor: pointer;\r\n");
      out.write("      }\r\n");
      out.write("      #mainImg a:hover{\r\n");
      out.write("         background-color: #EAEAEA;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      #sel3{\r\n");
      out.write("         margin-left: 0%;  \r\n");
      out.write("         margin-top: 0%;      \r\n");
      out.write("         position: absolute;\r\n");
      out.write("         background-color: black;\r\n");
      out.write("         color: white;\r\n");
      out.write("         outline: 0;\r\n");
      out.write("         border: 0;\r\n");
      out.write("         font-size: 15px;  \r\n");
      out.write("      }\r\n");
      out.write("      #sel3:hover{\r\n");
      out.write("         background-color: white;\r\n");
      out.write("         cursor: pointer;\r\n");
      out.write("         color: black;\r\n");
      out.write("         outline: 0;\r\n");
      out.write("         border: 0;\r\n");
      out.write("      }\r\n");
      out.write("   </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery-3.1.0.min.js\"></script>\r\n");
      out.write("\t<title>Insert title here</title>\r\n");
      out.write("\t<style>\t\r\n");
      out.write("\t\t#back{\r\n");
      out.write("\t\t\tbackground-color: black;\r\n");
      out.write("\t\t\tmargin: -1%;  \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t#div1{\r\n");
      out.write("\t\t\twidth: 50%;\r\n");
      out.write("\t\t\theight: 20%;\r\n");
      out.write("\t\t\tmargin-left: 72%;\r\n");
      out.write("\t\t\tmargin-top: 1%;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t#div1 a{\r\n");
      out.write("\t\t\tposition: static;\t\t\t\r\n");
      out.write("\t\t\tcursor: pointer;\r\n");
      out.write("\t\t\tcolor: black;\r\n");
      out.write("\t\t\tfont-size: 20px;\r\n");
      out.write("\t\t\ttext-decoration: none;\t\r\n");
      out.write("\t\t\ttext-align:center;\r\n");
      out.write("\t\t\tcolor: white;\t\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#div1 a:hover {\r\n");
      out.write("\t\t\tbackground-color: white;\t\t\t\r\n");
      out.write("\t\t\tfont-size: 20px;\r\n");
      out.write("\t\t\tcolor: black;\r\n");
      out.write("\t\t\ttext-decoration: none;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t#div3{\r\n");
      out.write("\t\t\twidth: 50%;\r\n");
      out.write("\t\t\theight: 20%; \r\n");
      out.write("\t\t\tmargin-left: 85%;\r\n");
      out.write("\t\t\tmargin-top: 1%;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#div3 a{\r\n");
      out.write("\t\t\tposition: static;\t\t\t\r\n");
      out.write("\t\t\tcursor: pointer;\r\n");
      out.write("\t\t\tcolor: black;\r\n");
      out.write("\t\t\tfont-size: 20px;\r\n");
      out.write("\t\t\ttext-decoration: none;\t\r\n");
      out.write("\t\t\ttext-align:center;\r\n");
      out.write("\t\t\tcolor: white;\t\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#div3 a:hover {\r\n");
      out.write("\t\t\tbackground-color: white;\t\t\t\r\n");
      out.write("\t\t\tfont-size: 20px;\r\n");
      out.write("\t\t\tcolor: black;\r\n");
      out.write("\t\t\ttext-decoration: none;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t#select{\r\n");
      out.write("\t\t\tmargin-top: 0.5%;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t#mainimg{\r\n");
      out.write("\t\t\tposition: absolute;\r\n");
      out.write("\t\t\tcolor: white;\r\n");
      out.write("\t\t\tmargin-left: 1%;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#div2{\r\n");
      out.write("\t\t\tmargin-left: 15%;\t\t\t\r\n");
      out.write("\t\t\ttop: 1%;\r\n");
      out.write("\t\t\tborder-bottom: solid 1px black;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#div2 a{\r\n");
      out.write("\t\t\tposition: static;\t\t\t\r\n");
      out.write("\t\t\tcursor: pointer;\r\n");
      out.write("\t\t\tcolor: white;\r\n");
      out.write("\t\t\tfont-size: 20px;\r\n");
      out.write("\t\t\ttext-decoration: none;\t\r\n");
      out.write("\t\t\ttext-align:center;\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#div2 a:hover {\r\n");
      out.write("\t\t\tbackground-color: white;\r\n");
      out.write("\t\t\tcolor: black;\t\t\t\r\n");
      out.write("\t\t\tfont-size: 20px;\r\n");
      out.write("\t\t\ttext-decoration: none;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#div2 p{\r\n");
      out.write("\t\t\tmargin-left: 12%;\r\n");
      out.write("\t\t\tposition: absolute;\r\n");
      out.write("\t\t\tmargin-top: -1.5%;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#mainimg{\r\n");
      out.write("\t\t\tcursor: pointer;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tbutton{\r\n");
      out.write("\t\t\tcursor: pointer;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#selbtn{\r\n");
      out.write("\t\t\tborder: 0;\r\n");
      out.write("\t\t\tbackground-color: black;\r\n");
      out.write("\t\t\tcolor: white;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#selbtn:hover {\r\n");
      out.write("\t\t\tbackground-color: white;\r\n");
      out.write("\t\t\tcolor: black;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"overflow-x:hidden; overflow-y:auto;\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"back\" style=\"height: 58;\" > \r\n");
      out.write("\t<!-- img id=\"mainimg\"  src=\"resources/img.jpg\" width=\"200px;\" onclick=\"location.href='./'\"> -->\r\n");
      out.write("\t<h2 id=\"mainimg\" onclick=\"location.href='./'\"> 슈마니커</h2>\r\n");
      out.write("\t\t \r\n");
      out.write("\t\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"div2\" style=\"margin-top: 1%\"> \r\n");
      out.write("\t\t<a href=\"category\">카테고리</a>\r\n");
      out.write("\t\t<a href=\"speller\">맞춤 상품</a>\t\t\t\r\n");
      out.write("\t\t<p><input id=\"select\" type=\"text\"/><button id=\"selbtn\">검색</button></p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("/* \t$(\"#select\").click(function() {\r\n");
      out.write("\t\tif($(\"#selbtn\").css(\"diplay\")==\"none\"){\r\n");
      out.write("\t\t\t$(\"#selbtn\").css(\"diplay\", \"block\");\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$(\"#selbtn\").css(\"diplay\")==\"none\");\r\n");
      out.write("\t\t};\r\n");
      out.write("\t});\r\n");
      out.write("\t */\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   <div id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("      <div id=\"mainImg\" style=\"height: 200;\" class=\"cycle-slideshow\"; data-cycle-loader=\"wait\";    data-cycle-timeout=\"1000\">\r\n");
      out.write("      \r\n");
      out.write("         <a><input type=\"checkbox\" onclick=\"checkd()\" id=\"oper\" value=\"nike\">나이키</a>\r\n");
      out.write("         <a><input type=\"checkbox\" onclick=\"checkd()\" id=\"oper\" value=\"adidas\">아디다스</a>\r\n");
      out.write("         <a><input type=\"checkbox\" onclick=\"checkd()\" id=\"oper\" value=\"fila\">휠라</a>\r\n");
      out.write("         <a><input type=\"checkbox\" onclick=\"checkd()\" id=\"oper\" value=\"reebok\">리복</a>\r\n");
      out.write("         <a><input type=\"checkbox\" onclick=\"checkd()\" id=\"oper\" value=\"descente\">데쌍트</a></br></br></br></br>\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         <a><input type=\"checkbox\" onclick=\"checkd()\" id=\"oper\" value=\"남\">남</a>\r\n");
      out.write("         <a><input type=\"checkbox\" onclick=\"checkd()\" id=\"oper\" value=\"여\">여</a></br></br></br></br>\r\n");
      out.write("         \r\n");
      out.write("         <a><input type=\"checkbox\" onclick=\"checkd()\" id=\"oper\" value=\"운동화\">운동화</a>\r\n");
      out.write("         <a><input type=\"checkbox\" onclick=\"checkd()\" id=\"oper\" value=\"캔버스화\">캔버스화</a>\r\n");
      out.write("         <a><input type=\"checkbox\" onclick=\"checkd()\" id=\"oper\" value=\"구두\">구두</a>\r\n");
      out.write("         <a><input type=\"checkbox\" onclick=\"checkd()\" id=\"oper\" value=\"샌들\">샌들</a>\r\n");
      out.write("         <a><input type=\"checkbox\" onclick=\"checkd()\" id=\"oper\" value=\"하이힐\">하이힐</a>\r\n");
      out.write("         <a><input type=\"checkbox\" onclick=\"checkd()\" id=\"oper\" value=\"슬리퍼\">슬리퍼</a></br></br></br></br>\r\n");
      out.write("               \r\n");
      out.write("         <input type=\"button\" id=\"sel3\" value=\"완료\" onclick=\"sel3()\">\r\n");
      out.write("      </div>\r\n");
      out.write("      <br />\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      <h2>완료누르면 나오는 이미지들 </h2>\r\n");
      out.write("      <div class=\"newImg\">\r\n");
      out.write("         <div class=\"new\"></div>\r\n");
      out.write("         <div class=\"new\"></div>\r\n");
      out.write("         <div class=\"new\"></div>\r\n");
      out.write("         <div class=\"new\"></div>\r\n");
      out.write("         <div class=\"new\"></div>\r\n");
      out.write("         \r\n");
      out.write("         <div class=\"new\"></div>\r\n");
      out.write("         <div class=\"new\"></div>\r\n");
      out.write("         <div class=\"new\"></div>\r\n");
      out.write("         <div class=\"new\"></div>\r\n");
      out.write("         <div class=\"new\"></div>\r\n");
      out.write("         \r\n");
      out.write("      </div>\r\n");
      out.write("      <br />\r\n");
      out.write("      </div>\r\n");
      out.write("   \r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("   /* \r\n");
      out.write("   function checkd(){\r\n");
      out.write("       var checkbox = document.getElementById('oper');        \r\n");
      out.write("        $('#oper:checked').each(function() { \r\n");
      out.write("           console.log($(this).val());           \r\n");
      out.write("      });\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   function sel3() {\r\n");
      out.write("      $('#oper:checked').each(function() { \r\n");
      out.write("           console.log($(this).val());           \r\n");
      out.write("      });\r\n");
      out.write("   }\r\n");
      out.write(" */\r\n");
      out.write(" function checkd() {\r\n");
      out.write("\t var checkbox = document.getElementById('oper');\r\n");
      out.write("\t $('#oper:checked').each(function() {\r\n");
      out.write("\t\tconsole.log($(this).val());\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(" function sel3() {\r\n");
      out.write("\t$('#oper:checked').each(function() {\r\n");
      out.write("\t\tconsole.log($(this).val());\r\n");
      out.write("\t})\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/./head.jsp(124,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginId == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t<div id=\"div3\">\t\t\r\n");
          out.write("\t\t<a href=\"./joinForm\">회원가입</a>\r\n");
          out.write("\t\t<a href=\"./index\">로그인</a>\r\n");
          out.write("\t\t<a href=\"#\">공지사항</a><br/>\r\n");
          out.write("\t</div>\t\r\n");
          out.write("\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/./head.jsp(132,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginId != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t<div id=\"div1\">\t\t\r\n");
          out.write("\t\t<a href=\"./logout\">로그아웃</a>\r\n");
          out.write("\t\t<a href=\"./mypage?id='");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("'\">마이페이지</a>\r\n");
          out.write("\t\t<a href=\"#\">공지사항</a>\r\n");
          out.write("\t\t<a href=\"#\">요청게시판</a>\r\n");
          out.write("\t\t<a href=\"#\">찜목록</a><br/>\r\n");
          out.write("\t</div>\t\r\n");
          out.write("\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/./head.jsp(142,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginId == 'admin'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t<div id=\"div1\">\t\t\r\n");
          out.write("\t\t<a href=\"adminpage\">관리자 페이지</a>\r\n");
          out.write("\t\t<a href=\"#\">로그아웃</a>\r\n");
          out.write("\t\t<a href=\"#\">마이페이지</a>\r\n");
          out.write("\t\t<a href=\"#\">공지사항</a>\r\n");
          out.write("\t\t<a href=\"#\">요청게시판</a>\r\n");
          out.write("\t\t<a href=\"#\">찜목록</a><br/>\r\n");
          out.write("\t</div>\t\r\n");
          out.write("\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }
}
