/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.30
 * Generated at: 2018-07-18 01:57:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class joinForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/FinalProjecthee/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/final/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1531184863091L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>슈마니커 회원가입</title>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<script src=\"http://dmaps.daum.net/map_js_init/postcode.v2.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\t#tab1{\r\n");
      out.write("\t\tmargin-left: 43.5%; \r\n");
      out.write("\t\tmargin-top: 5%;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t#tab1 table{\r\n");
      out.write("\t\tmargin-left: -15%; \r\n");
      out.write("\t\tborder-spacing: 10px;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#overlay{\r\n");
      out.write("\t\tborder: 0;\r\n");
      out.write("\t\toutline: 0;\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t\tbackground-color: black;\r\n");
      out.write("\t\tcolor: white;\r\n");
      out.write("\t\theight: 20px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#overlay:hover{\r\n");
      out.write("\t\tbackground-color: white;\r\n");
      out.write("\t\tcolor: black;\r\n");
      out.write("\t}\r\n");
      out.write("\t#tab3{\r\n");
      out.write("\t\theight: 60%;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t#point{\r\n");
      out.write("\t\tborder: 0;\r\n");
      out.write("\t\toutline: 0;\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t\tbackground-color: black;\r\n");
      out.write("\t\tcolor: white;\r\n");
      out.write("\t\theight: 20px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#point:hover{\r\n");
      out.write("\t\tbackground-color: white;\r\n");
      out.write("\t\tcolor: black;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#email_send{\r\n");
      out.write("\t\tborder: 0;\r\n");
      out.write("\t\toutline: 0;\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t\tbackground-color: black;\r\n");
      out.write("\t\tmargin-left: 1%;\r\n");
      out.write("\t\tcolor: white;\r\n");
      out.write("\t\theight: 20px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#email_send:hover{\r\n");
      out.write("\t\tbackground-color: white;\r\n");
      out.write("\t\tcolor: black;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t#join{\r\n");
      out.write("\t\tborder: 0;\r\n");
      out.write("\t\toutline: 0;\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t\tbackground-color: black;\r\n");
      out.write("\t\tmargin-left: 25%;\r\n");
      out.write("\t\tcolor: white;\r\n");
      out.write("\t\theight: 30px;\r\n");
      out.write("\t\twidth: 80px;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t#join:hover{\r\n");
      out.write("\t\tbackground-color: white;\r\n");
      out.write("\t\tcolor: black;\r\n");
      out.write("\t}\r\n");
      out.write("\t#size{\r\n");
      out.write("\t\tmargin-left: 1.5%;\r\n");
      out.write("\t}\r\n");
      out.write("\t#question{\r\n");
      out.write("\t\twidth: 38%;\r\n");
      out.write("\t\theight: 32%; \t\t \r\n");
      out.write("\t}\r\n");
      out.write("\t#answer{\r\n");
      out.write("\t\tmargin-left: 1%;\r\n");
      out.write("\t}\r\n");
      out.write("\t#tab3 a{\r\n");
      out.write("\t\tmargin-top: -5%;\r\n");
      out.write("\t}\r\n");
      out.write("\t#mainimg{\t\t\r\n");
      out.write("\t\tmargin-left: 45%;\r\n");
      out.write("\t\tmargin-top: 5%;\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t}\r\n");
      out.write("\t#add{\r\n");
      out.write("\t\tborder: 0;\r\n");
      out.write("\t\toutline: 0;\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t\tbackground-color: black;\r\n");
      out.write("\t\tcolor: white;\r\n");
      out.write("\t\theight: 70%;\r\n");
      out.write("\t\twidth: 21%; \r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t#add:hover{\r\n");
      out.write("\t\tbackground-color: white;\r\n");
      out.write("\t\tcolor: black;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("/* table, td, th {\r\n");
      out.write("\tborder: 1px solid black;\r\n");
      out.write("\tborder-collapse: collapse;\r\n");
      out.write("\tpadding: 5px 10px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\twidth: 1000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input.inputTxt {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("} */\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<h2 id=\"mainimg\" onclick=\"location.href='./'\">슈마니커</h2>\r\n");
      out.write("\r\n");
      out.write("<div id=\"tab1\">\r\n");
      out.write("\t<table>\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>아이디</td> \r\n");
      out.write("\t\t\t<td><input style=\"width: 171.7\" type=\"text\" name=\"userId\"\r\n");
      out.write("\t\t\t\tplaceholder=\"아이디 입력란\" /> <input id=\"overlay\" type=\"button\"\r\n");
      out.write("\t\t\t\tvalue=\"중복 체크\" /></td>\r\n");
      out.write("\t\t</tr> \r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>비밀번호</td>\r\n");
      out.write("\t\t\t<td><input class=\"inputTxt\" type=\"password\" name=\"userPw\"\r\n");
      out.write("\t\t\t\tplaceholder=\"비밀번호 입력란\" /></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>비밀번호 확인</td>\r\n");
      out.write("\t\t\t<td><input class=\"inputTxt\" type=\"password\" name=\"userPwCk\"\r\n");
      out.write("\t\t\t\tplaceholder=\"비밀번호 확인란\" /></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>이름</td>\r\n");
      out.write("\t\t\t<td><input class=\"inputTxt\" type=\"text\" name=\"userName\"\r\n");
      out.write("\t\t\t\tplaceholder=\"이름 입력란\" /></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>성별</td>\r\n");
      out.write("\t\t\t<td><input type=\"radio\" name=\"gender\" value=\"남성\" /> 남성 <input\r\n");
      out.write("\t\t\t\ttype=\"radio\" name=\"gender\" value=\"여성\" /> 여성</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>신발 사이즈</td>\r\n");
      out.write("\t\t\t<td><input type=\"text\" id=\"sizeview\" name=\"sizeview\"\r\n");
      out.write("\t\t\t\tstyle=\"width: 171.5\" placeholder=\"사이즈를 선택하세요.\" disabled=\"true\" /><select\r\n");
      out.write("\t\t\t\tid=\"size\">\r\n");
      out.write("\t\t\t\t\t<option value=\"0\">신발 사이즈를 선택하세요.</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"1\">직접입력</option>\r\n");
      out.write("\t\t\t\t\t<option>210mm</option>\r\n");
      out.write("\t\t\t\t\t<option>215mm</option>\r\n");
      out.write("\t\t\t\t\t<option>220mm</option>\r\n");
      out.write("\t\t\t\t\t<option>225mm</option>\r\n");
      out.write("\t\t\t\t\t<option>230mm</option>\r\n");
      out.write("\t\t\t\t\t<option>235mm</option>\r\n");
      out.write("\t\t\t\t\t<option>240mm</option>\r\n");
      out.write("\t\t\t\t\t<option>245mm</option>\r\n");
      out.write("\t\t\t\t\t<option>250mm</option>\r\n");
      out.write("\t\t\t\t\t<option>255mm</option>\r\n");
      out.write("\t\t\t\t\t<option>260mm</option>\r\n");
      out.write("\t\t\t\t\t<option>265mm</option>\r\n");
      out.write("\t\t\t\t\t<option>270mm</option>\r\n");
      out.write("\t\t\t\t\t<option>275mm</option>\r\n");
      out.write("\t\t\t\t\t<option>280mm</option>\r\n");
      out.write("\t\t\t\t\t<option>285mm</option>\r\n");
      out.write("\t\t\t\t\t<option>290mm</option>\r\n");
      out.write("\t\t\t\t\t<option>295mm</option>\r\n");
      out.write("\t\t\t\t\t<option>300mm</option>\r\n");
      out.write("\t\t\t</select></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>주소</td>\r\n");
      out.write("\t\t\t<td><input type=\"text\" name=\"addr1\" id=\"sample4_postcode\"\r\n");
      out.write("\t\t\t\tplaceholder=\"우편번호\"> <input type=\"button\" id=\"add\"\r\n");
      out.write("\t\t\t\tonclick=\"sample4_execDaumPostcode()\" value=\"우편번호 찾기\"> <br>\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"addr2\" id=\"sample4_roadAddress\"\r\n");
      out.write("\t\t\t\tplaceholder=\"도로명주소\"> <input type=\"text\" name=\"addr3\"\r\n");
      out.write("\t\t\t\tid=\"sample4_jibunAddress\" placeholder=\"지번주소\"> <span\r\n");
      out.write("\t\t\t\tid=\"guide\" style=\"color: #999\"></span></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>EMAIL</td>\r\n");
      out.write("\t\t\t<td><input class=\"inputTxt\" type=\"text\" name=\"email\" \r\n");
      out.write("\t\t\t\tid=\"first_email\" style=\"width: 171.5\" placeholder=\"이메일 입력란\" /> @ <input\r\n");
      out.write("\t\t\t\ttype=\"text\" id=\"emailview\" name=\"emailview\" style=\"width: 100\"\r\n");
      out.write("\t\t\t\tplaceholder=\"이메일 선택\" disabled=\"true\" /> <select id=\"email\">\r\n");
      out.write("\t\t\t\t\t<option value=\"0\">이메일을 선택 하세요</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"1\">직접입력</option>\r\n");
      out.write("\t\t\t\t\t<option>naver.com</option>\r\n");
      out.write("\t\t\t\t\t<option>hanmail.net</option>\r\n");
      out.write("\t\t\t\t\t<option>google.com</option>\r\n");
      out.write("\t\t\t\t\t<option>nate.com</option>\r\n");
      out.write("\t\t\t\t\t<option>daum.net</option>\r\n");
      out.write("\t\t\t</select></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>본인 확인 절차</td>\r\n");
      out.write("\t\t\t<td><input type=\"text\" style=\"color: red\" name=\"email_enter\"\r\n");
      out.write("\t\t\t\tid=\"email_enter\" value=\"이메일 인증이 필요합니다.\" disabled=\"true\" /><input\r\n");
      out.write("\t\t\t\ttype=\"button\" id=\"email_send\" name=\"email_send\" value=\"이메일 인증\" /></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>휴대폰 번호</td>\r\n");
      out.write("\t\t\t<td><input class=\"inputTxt\" type=\"text\" name=\"phone\"\r\n");
      out.write("\t\t\t\tplaceholder=\"휴대폰 번호 입력란\" /></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>본인인증 질문</td>\r\n");
      out.write("\t\t\t<td><select id=\"question\">\r\n");
      out.write("\t\t\t\t\t<option value=\"0\">질문을 선택하세요.</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"나의 보물 1호는?\">나의 보물 1호는?</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"출신 고등학교는?\">출신 고등학교는?</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"유년시절 내가 살던 동네는?\">유년시절 내가 살던 동네는?</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"가장 친한 친구의 이름은?\">가장 친한 친구의 이름은?</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"나의 별명은?\">나의 별명은?</option>\r\n");
      out.write("\t\t\t</select><input type=\"text\" name=\"answer\" id=\"answer\" placeholder=\"질문 답변\" /></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t<button id=\"join\">회원가입</button>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("var idReg = /^[a-z]+[a-z0-9]{5,19}$/g;\r\n");
      out.write("var pwReg = /^[a-z]+[a-z0-9]{7,15}$/g;\r\n");
      out.write("\r\n");
      out.write("var obj = {};//초기화   \r\n");
      out.write("obj.type = \"post\";\r\n");
      out.write("obj.dataType = \"json\";\r\n");
      out.write("obj.enctype = \"multipart/form-data\";\r\n");
      out.write("obj.error = function(e) {\r\n");
      out.write("\tconsole.log(e)\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("var openWin;\r\n");
      out.write("$(\"#email_send\")\r\n");
      out.write("\t\t.click(\r\n");
      out.write("\t\t\t\tfunction() {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t// window.name = \"부모창 이름\"; \r\n");
      out.write("\t\t\t\t\twindow.name = \"parentForm\";\r\n");
      out.write("\t\t\t\t\t//window.open(\"open할 window\", \"자식창 이름\", \"팝업창 옵션\");\r\n");
      out.write("\t\t\t\t\topenWin = window\r\n");
      out.write("\t\t\t\t\t\t\t.open(\"./mail_check\", \"childForm\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"width=700, height=200, resizable = no, scrollbars = no, left = 300, top= 200\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("$(\"#email\").change(function() {\r\n");
      out.write("\t$(\"#email option:selected\").each(function() {\r\n");
      out.write("\r\n");
      out.write("\t\tif ($(this).val() == '0') {\r\n");
      out.write("\t\t\t$(\"#emailview\").val(\"이메일 입력란\");\r\n");
      out.write("\t\t\t$(\"#emailview\").attr(\"disabled\", true);\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\telse if ($(this).val() == '1') { //직접입력일 경우\r\n");
      out.write("\t\t\t$(\"#emailview\").val(''); //값 초기화\r\n");
      out.write("\t\t\t$(\"#emailview\").attr(\"placeholder\", \"직접입력\");\r\n");
      out.write("\t\t\t$(\"#emailview\").attr(\"disabled\", false); //활성화 \r\n");
      out.write("\t\t} else { //직접입력이 아닐경우 \r\n");
      out.write("\t\t\t$(\"#emailview\").val($(this).text()); //선택값 입력\r\n");
      out.write("\t\t\t$(\"#emailview\").attr(\"disabled\", true); //비활성화\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(\"#size\").change(function() {\r\n");
      out.write("\t$(\"#size option:selected\").each(function() {\r\n");
      out.write("\r\n");
      out.write("\t\tif ($(this).val() == '0') {\r\n");
      out.write("\t\t\t$(\"#sizeview\").val(\"사이즈를 선택하세요.\");\r\n");
      out.write("\t\t\t$(\"#sizeview\").attr(\"disabled\", true);\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\telse if ($(this).val() == '1') { //직접입력일 경우\r\n");
      out.write("\t\t\t$(\"#sizeview\").val('mm'); //값 초기화\r\n");
      out.write("\t\t\t$(\"#sizeview\").attr(\"placeholder\", \"직접입력\");\r\n");
      out.write("\t\t\t$(\"#sizeview\").attr(\"disabled\", false); //활성화 \r\n");
      out.write("\t\t} else { //직접입력이 아닐경우 \r\n");
      out.write("\t\t\t$(\"#sizeview\").val($(this).text()); //선택값 입력\r\n");
      out.write("\t\t\t$(\"#sizeview\").attr(\"disabled\", true); //비활성화\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("var overChk = false;//중복체크 값\r\n");
      out.write("$(\"#overlay\").click(function() {\r\n");
      out.write("\tvar userId = $(\"input[name=userId]\").val();\r\n");
      out.write("\r\n");
      out.write("\tobj.url = \"./overlay\";\r\n");
      out.write("\tobj.data = {\r\n");
      out.write("\t\tid : $(\"input[name='userId']\").val()\r\n");
      out.write("\t};\r\n");
      out.write("\tobj.success = function(d) {\r\n");
      out.write("\t\tconsole.log(d.overlay);\r\n");
      out.write("\r\n");
      out.write("\t\tif (!idReg.test(userId)) {\r\n");
      out.write("\t\t\talert(\"아이디는 영문자로 시작하는 6~20자 영문자 또는 숫자이어야 합니다.\");\r\n");
      out.write("\t\t\t$(\"input[name='userId']\").focus();\r\n");
      out.write("\t\t\t$(\"input[name='userId']\").val(\"\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if (d.overlay) {\r\n");
      out.write("\t\t\talert(\"사용중인 아이디 입니다.\");\r\n");
      out.write("\t\t\t$(\"input[name='userId']\").val(\"\");\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\talert(\"사용 가능한 아이디 입니다.\");\r\n");
      out.write("\t\t\t$(\"input[name='userId']\").css(\"color\", \"green\");\r\n");
      out.write("\t\t\t$(\"input[name='userId']\").attr(\"disabled\", true);\r\n");
      out.write("\t\t\toverChk = true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t};\r\n");
      out.write("\tconsole.log(obj);\r\n");
      out.write("\tajaxCall(obj);\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(\"#join\")\r\n");
      out.write("\t\t.click(\r\n");
      out.write("\t\t\t\tfunction() {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tif (!overChk) {\r\n");
      out.write("\t\t\t\t\t\talert(\"아이디 중복 체크를 실행 해 주세요!\");\r\n");
      out.write("\t\t\t\t\t\t$(\"input[name='userId']\").focus();//포커스 이동\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tif ($(\"input[name='userPw']\").val() == \"\") {//비밀번호 입력 확인\r\n");
      out.write("\t\t\t\t\t\t\talert(\"비밀 번호를 확인 해 주세요!\");\r\n");
      out.write("\t\t\t\t\t\t\t$(\"input[name='userPw']\").focus();//포커스 이동\r\n");
      out.write("\t\t\t\t\t\t}else if (!idReg.test($(\"input[name='userPw']\").val())) {\r\n");
      out.write("\t\t\t\t\t\t\talert(\"비밀번호는 영문자로 시작하는 8~16자 영문자 또는 숫자이어야 합니다.\");\r\n");
      out.write("\t\t\t\t\t\t\t$(\"input[name='userPw']\").focus();\r\n");
      out.write("\t\t\t\t\t\t\t$(\"input[name='userPw']\").val(\"\");\r\n");
      out.write("\t\t\t\t\t\t\t$(\"input[name='userPwCk']\").val(\"\");\r\n");
      out.write("\t\t\t\t\t\t}else if ($(\"input[name='userPwCk']\").val() == \"\") {//이름 입력 확인\r\n");
      out.write("\t\t\t\t\t\t\talert(\"비밀번호확인을  확인 해 주세요!\");\r\n");
      out.write("\t\t\t\t\t\t\t$(\"input[name='userPwCk']\").focus();//포커스 이동\r\n");
      out.write("\t\t\t\t\t\t} else if ($(\"input[name='userPw']\").val() != $(\r\n");
      out.write("\t\t\t\t\t\t\t\t\"input[name='userPwCk']\").val()) {//이름 입력 확인\r\n");
      out.write("\t\t\t\t\t\t\talert(\"비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("\t\t\t\t\t\t\t$(\"input[name='userPw']\").focus();//포커스 이동\r\n");
      out.write("\t\t\t\t\t\t} else if ($(\"input[name='userName']\").val() == \"\") {//이름 입력 확인\r\n");
      out.write("\t\t\t\t\t\t\talert(\"이름을 확인 해 주세요!\");\r\n");
      out.write("\t\t\t\t\t\t\t$(\"input[name='userName']\").focus();//포커스 이동\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t} else if ($(\"input[name='sizeview']\").val() == \"\") {\r\n");
      out.write("\t\t\t\t\t\t\talert(\"사이즈를 확인 해 주세요!\");\r\n");
      out.write("\t\t\t\t\t\t\t$(\"input[name='sizeview']\").focus();//포커스 이동\r\n");
      out.write("\t\t\t\t\t\t} else if ($(\"input[name='addr1']\").val() == \"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t|| $(\"input[name='addr2']\").val() == \"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t|| $(\"input[name='addr3']\").val() == \"\") {//주소 입력 확인\r\n");
      out.write("\t\t\t\t\t\t\talert(\"주소를 확인 해 주세요!\");\r\n");
      out.write("\t\t\t\t\t\t\t$(\"input[name='userAge']\").focus();//포커스 이동\r\n");
      out.write("\t\t\t\t\t\t} else if ($(\"input[name='email']\").val() == \"\") {//이메일 입력 확인\r\n");
      out.write("\t\t\t\t\t\t\talert(\"이메일을 확인 해 주세요!\");\r\n");
      out.write("\t\t\t\t\t\t\t$(\"input[name='email']\").focus();//포커스 이동\r\n");
      out.write("\t\t\t\t\t\t} else if ($(\"input[name='email_enter']\").val() == \"이메일 인증이 필요합니다.\") {\r\n");
      out.write("\t\t\t\t\t\t\talert(\"이메일 인증을 확인 해 주세요!\");\r\n");
      out.write("\t\t\t\t\t\t\t$(\"input[name='email_send']\").focus();//포커스 이동\r\n");
      out.write("\t\t\t\t\t\t} else if ($(\"input[name='phone']\").val() == \"\") {\r\n");
      out.write("\t\t\t\t\t\t\talert(\"핸드폰 번호를 확인 해 주세요!\");\r\n");
      out.write("\t\t\t\t\t\t\t$(\"input[name='phone']\").focus();//포커스 이동\r\n");
      out.write("\t\t\t\t\t\t} else if ($(\"#question\").val() == 0) {\r\n");
      out.write("\t\t\t\t\t\t\talert(\"본인 확인 질문을 확인 해 주세요!\");\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#question\").focus();//포커스 이동\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t/* else if(){\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t}  */\r\n");
      out.write("\t\t\t\t\t\telse {\r\n");
      out.write("\t\t\t\t\t\t\tconsole.log(\"서버 전송\");\r\n");
      out.write("\t\t\t\t\t\t\tobj.url = \"./join\";\r\n");
      out.write("\t\t\t\t\t\t\tobj.data.mem_id = $(\"input[name='userId']\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t.val();\r\n");
      out.write("\t\t\t\t\t\t\tobj.data.mem_pw = $(\"input[name='userPw']\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t.val();\r\n");
      out.write("\t\t\t\t\t\t\tobj.data.mem_name = $(\"input[name='userName']\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t.val();\r\n");
      out.write("\t\t\t\t\t\t\tobj.data.mem_gender = $(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"input[name='gender']:checked\").val();\r\n");
      out.write("\t\t\t\t\t\t\tobj.data.mem_size = $(\"input[name='sizeview']\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t.val();\r\n");
      out.write("\t\t\t\t\t\t\tobj.data.mem_email = $(\"input[name='email']\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t.val()\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ \"@\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ $(\"input[name=emailview]\").val();\r\n");
      out.write("\t\t\t\t\t\t\tobj.data.mem_addr1 = $(\"input[name='addr1']\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t.val();\r\n");
      out.write("\t\t\t\t\t\t\tobj.data.mem_addr2 = $(\"input[name='addr2']\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t.val();\r\n");
      out.write("\t\t\t\t\t\t\tobj.data.mem_addr3 = $(\"input[name='addr3']\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t.val();\r\n");
      out.write("\t\t\t\t\t\t\tobj.data.mem_phone = $(\"input[name='phone']\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t.val();\r\n");
      out.write("\t\t\t\t\t\t\tobj.data.mem_question = $(\"#question\").val();\r\n");
      out.write("\t\t\t\t\t\t\tobj.data.mem_answer = $(\"input[name='answer']\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t.val();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\tobj.success = function(data) {\r\n");
      out.write("\t\t\t\t\t\t\t\tif (data.success == 1) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\talert(\"회원 가입이 정상 처리 되었습니다.\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tlocation.href = \"./\";\r\n");
      out.write("\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\talert(\"회원 가입에 실패 했습니다.\");\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tconsole.log(obj);\r\n");
      out.write("\t\t\t\t\t\t\tajaxCall(obj);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("//전달 받은 오브젝트로 ajax 통신 실행\r\n");
      out.write("function ajaxCall(obj) {\r\n");
      out.write("\t$.ajax(obj);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function sample4_execDaumPostcode() {\r\n");
      out.write("\tnew daum.Postcode(\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\toncomplete : function(data) {\r\n");
      out.write("\t\t\t\t\t// 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t// 도로명 주소의 노출 규칙에 따라 주소를 조합한다.\r\n");
      out.write("\t\t\t\t\t// 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("\t\t\t\t\tvar fullRoadAddr = data.roadAddress; // 도로명 주소 변수\r\n");
      out.write("\t\t\t\t\tvar extraRoadAddr = ''; // 도로명 조합형 주소 변수\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t// 법정동명이 있을 경우 추가한다. (법정리는 제외)\r\n");
      out.write("\t\t\t\t\t// 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\r\n");
      out.write("\t\t\t\t\tif (data.bname !== '' && /[동|로|가]$/g.test(data.bname)) {\r\n");
      out.write("\t\t\t\t\t\textraRoadAddr += data.bname;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t// 건물명이 있고, 공동주택일 경우 추가한다.\r\n");
      out.write("\t\t\t\t\tif (data.buildingName !== '' && data.apartment === 'Y') {\r\n");
      out.write("\t\t\t\t\t\textraRoadAddr += (extraRoadAddr !== '' ? ', '\r\n");
      out.write("\t\t\t\t\t\t\t\t+ data.buildingName : data.buildingName);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t// 도로명, 지번 조합형 주소가 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\r\n");
      out.write("\t\t\t\t\tif (extraRoadAddr !== '') {\r\n");
      out.write("\t\t\t\t\t\textraRoadAddr = ' (' + extraRoadAddr + ')';\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t// 도로명, 지번 주소의 유무에 따라 해당 조합형 주소를 추가한다.\r\n");
      out.write("\t\t\t\t\tif (fullRoadAddr !== '') {\r\n");
      out.write("\t\t\t\t\t\tfullRoadAddr += extraRoadAddr;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t// 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("\t\t\t\t\tdocument.getElementById('sample4_postcode').value = data.zonecode; //5자리 새우편번호 사용\r\n");
      out.write("\t\t\t\t\tdocument.getElementById('sample4_roadAddress').value = fullRoadAddr;\r\n");
      out.write("\t\t\t\t\tdocument.getElementById('sample4_jibunAddress').value = data.jibunAddress;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t// 사용자가 '선택 안함'을 클릭한 경우, 예상 주소라는 표시를 해준다.\r\n");
      out.write("\t\t\t\t\tif (data.autoRoadAddress) {\r\n");
      out.write("\t\t\t\t\t\t//예상되는 도로명 주소에 조합형 주소를 추가한다.\r\n");
      out.write("\t\t\t\t\t\tvar expRoadAddr = data.autoRoadAddress\r\n");
      out.write("\t\t\t\t\t\t\t\t+ extraRoadAddr;\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById('guide').innerHTML = '(예상 도로명 주소 : '\r\n");
      out.write("\t\t\t\t\t\t\t\t+ expRoadAddr + ')';\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t} else if (data.autoJibunAddress) {\r\n");
      out.write("\t\t\t\t\t\tvar expJibunAddr = data.autoJibunAddress;\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById('guide').innerHTML = '(예상 지번 주소 : '\r\n");
      out.write("\t\t\t\t\t\t\t\t+ expJibunAddr + ')';\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById('guide').innerHTML = '';\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}).open();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
