/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.30
 * Generated at: 2018-07-11 01:02:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class myinfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/FinalProjecthee/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/final/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1531270711351L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>판매자 정보 수정</title>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<script src=\"http://dmaps.daum.net/map_js_init/postcode.v2.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <!-- 바디 전체를 감싸는 updateForm 클래스 -->\r\n");
      out.write("   <div class=updateForm>\r\n");
      out.write("      <div class=userUpdateTitle>\r\n");
      out.write("         <br />\r\n");
      out.write("         <br />\r\n");
      out.write("         <h1>회원 정보 수정</h1>\r\n");
      out.write("      </div>\r\n");
      out.write("      <br />\r\n");
      out.write("      <!-- 기본 정보 뷰 -->\r\n");
      out.write("      <table class=updateFormTable id=\"before\">\r\n");
      out.write("         <br />\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td colspan=\"3\"><hr /></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>회원 이름</td>\r\n");
      out.write("            <td><input class=inp type=\"text\" name=\"userName\"\r\n");
      out.write("               id=\"beforeName\" disabled=\"true\" /></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>성별</td>\r\n");
      out.write("            <td><input type=\"text\" id=\"beforeGender\" disabled=\"true\"></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>신발 사이즈</td>\r\n");
      out.write("            <td><input type=\"text\" id=\"beforeSize\" disabled=\"true\"></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>회원 주소</td>\r\n");
      out.write("            <td><input class=inp type=\"text\" id=\"beforeAddr\"\r\n");
      out.write("               disabled=\"true\" style=\"width: 70%\" /></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>회원 EMAIL</td>\r\n");
      out.write("            <td><input class=inp type=\"text\" id=\"beforeEmail\"\r\n");
      out.write("               disabled=\"true\" /></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>회원 휴대폰 번호</td>\r\n");
      out.write("            <td><input class=inp type=\"text\" name=\"phone\" id=\"beforePhone\"\r\n");
      out.write("               disabled=\"true\" /></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td colspan=\"3\"><hr /></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td colspan=\"2\" style=\"text-align: right\">\r\n");
      out.write("               <button id=\"update_start\">정보 수정하기</button>\r\n");
      out.write("               <button id=\"update_end2\">취소</button>\r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("\r\n");
      out.write("      <!--    본인확인 완료 후 창 -->\r\n");
      out.write("      <table style=\"display: none;\" id=\"after\">\r\n");
      out.write("\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td colspan=\"3\"><hr /></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>새로운 비밀번호</td>\r\n");
      out.write("            <td><input class=\"inp\" type=\"password\" name=\"userPw\"\r\n");
      out.write("               placeholder=\"비밀번호 입력란\" /></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>새로운 비밀번호 확인</td>\r\n");
      out.write("            <td><input class=inp type=\"password\" name=\"userPwCk\"\r\n");
      out.write("               placeholder=\"비밀번호 확인란\" /></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>새로운 이름</td>\r\n");
      out.write("            <td><input class=inp type=\"text\" name=\"after_userName\"\r\n");
      out.write("               id=\"after_userName\" placeholder=\"이름 입력란\" /></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>성별</td>\r\n");
      out.write("            <td><input type=\"radio\" name=\"gender\" value=\"남성\" /> 남성 <input\r\n");
      out.write("               type=\"radio\" name=\"gender\" value=\"여성\" /> 여성</td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>신발 사이즈</td>\r\n");
      out.write("            <td><input type=\"text\" id=\"sizeview\" name=\"sizeview\"\r\n");
      out.write("               style=\"width: 200\" placeholder=\"사이즈를 선택하세요.\" disabled=\"true\" /><select\r\n");
      out.write("               id=\"size\">\r\n");
      out.write("                  <option value=\"0\">신발 사이즈를 선택하세요.</option>\r\n");
      out.write("                  <option value=\"1\">직접입력</option>\r\n");
      out.write("                  <option>210mm</option>\r\n");
      out.write("                  <option>215mm</option>\r\n");
      out.write("                  <option>220mm</option>\r\n");
      out.write("                  <option>225mm</option>\r\n");
      out.write("                  <option>230mm</option>\r\n");
      out.write("                  <option>235mm</option>\r\n");
      out.write("                  <option>240mm</option>\r\n");
      out.write("                  <option>245mm</option>\r\n");
      out.write("                  <option>250mm</option>\r\n");
      out.write("                  <option>255mm</option>\r\n");
      out.write("                  <option>260mm</option>\r\n");
      out.write("                  <option>265mm</option>\r\n");
      out.write("                  <option>270mm</option>\r\n");
      out.write("                  <option>275mm</option>\r\n");
      out.write("                  <option>280mm</option>\r\n");
      out.write("                  <option>285mm</option>\r\n");
      out.write("                  <option>290mm</option>\r\n");
      out.write("                  <option>295mm</option>\r\n");
      out.write("                  <option>300mm</option>\r\n");
      out.write("            </select></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>새로운 주소</td>\r\n");
      out.write("            <td><input class=inp type=\"text\" name=\"addr1\"\r\n");
      out.write("               id=\"sample4_postcode\" placeholder=\"우편번호\" style=\"margin: 4 0 4 0\">\r\n");
      out.write("               <input type=\"button\" class=inp id=\"path\"\r\n");
      out.write("               onclick=\"sample4_execDaumPostcode()\" value=\"우편번호 찾기\"> <br>\r\n");
      out.write("               <input type=\"text\" class=inp name=\"addr2\" id=\"sample4_roadAddress\"\r\n");
      out.write("               placeholder=\"도로명주소\" style=\"margin: 4 0 4 0\"> <input\r\n");
      out.write("               type=\"text\" class=inp name=\"addr3\" id=\"sample4_jibunAddress\"\r\n");
      out.write("               placeholder=\"지번주소\" style=\"margin: 4 0 4 0\"> <span\r\n");
      out.write("               id=\"guide\" style=\"color: #999\"></span></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>새로운 EMAIL</td>\r\n");
      out.write("            <td><input class=inp type=\"text\" name=\"after_email\"\r\n");
      out.write("               id=\"after_email\" style=\"margin: 0 5 0 0\" placeholder=\"이메일 입력란\" />\r\n");
      out.write("               @ <input class=inp type=\"text\" id=\"emailview\"\r\n");
      out.write("               name=\"after_emailview\" style=\"width: 150\" placeholder=\"이메일 선택\"\r\n");
      out.write("               disabled=\"true\" /> <select id=\"email\">\r\n");
      out.write("                  <option value=\"0\">이메일 선택</option>\r\n");
      out.write("                  <option value=\"1\">직접입력</option>\r\n");
      out.write("                  <option>naver.com</option>\r\n");
      out.write("                  <option>hanmail.net</option>\r\n");
      out.write("                  <option>google.com</option>\r\n");
      out.write("                  <option>nate.com</option>\r\n");
      out.write("                  <option>daum.net</option>\r\n");
      out.write("            </select></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>새로운 휴대폰 번호</td>\r\n");
      out.write("            <td><input class=inp type=\"text\" name=\"after_phone\"\r\n");
      out.write("               id=\"after_phone\" placeholder=\"휴대폰 번호 입력란\" /></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td colspan=\"2\" style=\"text-align: right\">\r\n");
      out.write("               <button id=\"update_success\">저장</button>\r\n");
      out.write("               <button id=\"update_end1\">취소</button>\r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("   </div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("   var obj = {};//초기화   \r\n");
      out.write("   obj.type = \"post\";\r\n");
      out.write("   obj.dataType = \"json\";\r\n");
      out.write("   obj.enctype = \"multipart/form-data\";\r\n");
      out.write("   obj.data = {};\r\n");
      out.write("   obj.error = function(e) {\r\n");
      out.write("      console.log(e)\r\n");
      out.write("   };\r\n");
      out.write("\r\n");
      out.write("   var pwReg = /^[a-z]+[a-z0-9]{7,15}$/g;\r\n");
      out.write("\r\n");
      out.write("   $(document).ready(function() {\r\n");
      out.write("      obj.url = \"./detailView\";\r\n");
      out.write("      obj.success = function(data) {\r\n");
      out.write("         $(\"#beforeName\").val(data.dto.mem_name);\r\n");
      out.write("         $(\"#beforeEmail\").val(data.dto.mem_email);\r\n");
      out.write("         $(\"#beforeSize\").val(data.dto.mem_size);\r\n");
      out.write("         $(\"#beforeGender\").val(data.dto.mem_gender);\r\n");
      out.write("         $(\"#beforeAddr\").val(data.dto.mem_addr);\r\n");
      out.write("         $(\"#beforePhone\").val(data.dto.mem_phone);\r\n");
      out.write("\r\n");
      out.write("         var addrSplit = data.dto.mem_addr.split('/');\r\n");
      out.write("\r\n");
      out.write("         var emailSplit = data.dto.mem_email.split('@');\r\n");
      out.write("\r\n");
      out.write("         $(\"#after_userName\").val(data.dto.mem_name);\r\n");
      out.write("         $(\"#sizeview\").val(data.dto.mem_size);\r\n");
      out.write("         $(\"#after_email\").val(emailSplit[0]);\r\n");
      out.write("         $(\"#emailview\").val(emailSplit[1]);\r\n");
      out.write("         $(\"#after_phone\").val(data.dto.mem_phone);\r\n");
      out.write("         $(\"#sample4_postcode\").val(addrSplit[0]);\r\n");
      out.write("         $(\"#sample4_roadAddress\").val(addrSplit[1]);\r\n");
      out.write("         $(\"#sample4_jibunAddress\").val(addrSplit[2]);\r\n");
      out.write("\r\n");
      out.write("         if (data.login) {\r\n");
      out.write("            alert(\"본인 확인 후 수정이 가능합니다.\");\r\n");
      out.write("         } else {\r\n");
      out.write("            alert(\"로그인이 필요한 서비스 입니다.\");\r\n");
      out.write("            location.href = \"index.html\";\r\n");
      out.write("         }\r\n");
      out.write("      }\r\n");
      out.write("      ajaxCall(obj);\r\n");
      out.write("   });\r\n");
      out.write("\r\n");
      out.write("   $(\"#update_end1\").click(function() {\r\n");
      out.write("      location.href = \"updateform.jsp\";\r\n");
      out.write("   });\r\n");
      out.write("\r\n");
      out.write("   $(\"#update_end2\").click(function() {\r\n");
      out.write("      location.href = \"main.jsp\";\r\n");
      out.write("   });\r\n");
      out.write("\r\n");
      out.write("   $(\"#email\").change(function() {\r\n");
      out.write("      $(\"#email option:selected\").each(function() {\r\n");
      out.write("\r\n");
      out.write("         if ($(this).val() == '0') {\r\n");
      out.write("            $(\"#emailview\").val(\"이메일 입력란\");\r\n");
      out.write("            $(\"#emailview\").attr(\"disabled\", true);\r\n");
      out.write("         }\r\n");
      out.write("\r\n");
      out.write("         else if ($(this).val() == '1') { //직접입력일 경우\r\n");
      out.write("            $(\"#emailview\").val(''); //값 초기화\r\n");
      out.write("            $(\"#emailview\").attr(\"placeholder\", \"직접입력\");\r\n");
      out.write("            $(\"#emailview\").attr(\"disabled\", false); //활성화 \r\n");
      out.write("         } else { //직접입력이 아닐경우 \r\n");
      out.write("            $(\"#emailview\").val($(this).text()); //선택값 입력\r\n");
      out.write("            $(\"#emailview\").attr(\"disabled\", true); //비활성화\r\n");
      out.write("         }\r\n");
      out.write("      });\r\n");
      out.write("   });\r\n");
      out.write("\r\n");
      out.write("   $(\"#size\").change(function() {\r\n");
      out.write("      $(\"#size option:selected\").each(function() {\r\n");
      out.write("\r\n");
      out.write("         if ($(this).val() == '0') {\r\n");
      out.write("            $(\"#sizeview\").val(\"사이즈를 선택하세요.\");\r\n");
      out.write("            $(\"#sizeview\").attr(\"disabled\", true);\r\n");
      out.write("         }\r\n");
      out.write("\r\n");
      out.write("         else if ($(this).val() == '1') { //직접입력일 경우\r\n");
      out.write("            $(\"#sizeview\").val('mm'); //값 초기화\r\n");
      out.write("            $(\"#sizeview\").attr(\"placeholder\", \"직접입력\");\r\n");
      out.write("            $(\"#sizeview\").attr(\"disabled\", false); //활성화 \r\n");
      out.write("         } else { //직접입력이 아닐경우 \r\n");
      out.write("            $(\"#sizeview\").val($(this).text()); //선택값 입력\r\n");
      out.write("            $(\"#sizeview\").attr(\"disabled\", true); //비활성화\r\n");
      out.write("         }\r\n");
      out.write("      });\r\n");
      out.write("   });\r\n");
      out.write("\r\n");
      out.write("   $(\"#update_start\")\r\n");
      out.write("         .click(\r\n");
      out.write("               function() {\r\n");
      out.write("                  // window.name = \"부모창 이름\"; \r\n");
      out.write("                  window.name = \"parentForm\";\r\n");
      out.write("                  //window.open(\"open할 window\", \"자식창 이름\", \"팝업창 옵션\");\r\n");
      out.write("                  openWin = window\r\n");
      out.write("                        .open(\"./updateChk\", \"childForm\",\r\n");
      out.write("                              \"width=550, height=250, resizable = no, scrollbars = no\");\r\n");
      out.write("\r\n");
      out.write("               });\r\n");
      out.write("\r\n");
      out.write("   $(\"#update_success\")\r\n");
      out.write("         .click(\r\n");
      out.write("               function() {\r\n");
      out.write("\r\n");
      out.write("                  if ($(\"input[name='userPw']\").val() == \"\") {//비밀번호 입력 확인\r\n");
      out.write("                     alert(\"비밀 번호를 확인 해 주세요!\");\r\n");
      out.write("                     $(\"input[name='userPw']\").focus();//포커스 이동\r\n");
      out.write("                  } else if ($(\"input[name='userPwCk']\").val() == \"\") {//이름 입력 확인\r\n");
      out.write("                     alert(\"비밀번호확인을  확인 해 주세요!\");\r\n");
      out.write("                     $(\"input[name='userPwCk']\").focus();//포커스 이동\r\n");
      out.write("                  } else if (!pwReg.test($(\"input[name='userPw']\").val())) {\r\n");
      out.write("                     alert(\"비밀번호는 영문자로 시작하는 8~16자 영문자 또는 숫자이어야 합니다.\");\r\n");
      out.write("                     $(\"input[name='userPw']\").focus();\r\n");
      out.write("                     $(\"input[name='userPw']\").val(\"\");\r\n");
      out.write("                     $(\"input[name='userPwCk']\").val(\"\");\r\n");
      out.write("                  } else if ($(\"input[name='userPw']\").val() != $(\r\n");
      out.write("                        \"input[name='userPwCk']\").val()) {//이름 입력 확인\r\n");
      out.write("                     alert(\"비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("                     $(\"input[name='userPw']\").focus();//포커스 이동\r\n");
      out.write("                  } else if ($(\"input[name='after_userName']\").val() == \"\") {//이름 입력 확인\r\n");
      out.write("                     alert(\"이름을 확인 해 주세요!\");\r\n");
      out.write("                     $(\"input[name='after_userName']\").focus();//포커스 이동\r\n");
      out.write("                  } else if ($(\"input[name='sizeview']\").val() == \"\") {\r\n");
      out.write("                     alert(\"사이즈를 확인 해 주세요!\");\r\n");
      out.write("                     $(\"input[name='sizeview']\").focus();//포커스 이동\r\n");
      out.write("                  } else if ($(\"input[name='addr1']\").val() == \"\"\r\n");
      out.write("                        || $(\"input[name='addr2']\").val() == \"\"\r\n");
      out.write("                        || $(\"input[name='addr3']\").val() == \"\") {//주소 입력 확인\r\n");
      out.write("                     alert(\"주소를 확인 해 주세요!\");\r\n");
      out.write("                     $(\"input[name='addr1']\").focus();//포커스 이동\r\n");
      out.write("                  } else if ($(\"input[name='after_email']\").val() == \"\") {//이메일 입력 확인\r\n");
      out.write("                     alert(\"이메일을 확인 해 주세요!\");\r\n");
      out.write("                     $(\"input[name='after_email']\").focus();//포커스 이동\r\n");
      out.write("                  } else if ($(\"input[name='after_phone']\").val() == \"\") {\r\n");
      out.write("                     alert(\"핸드폰 번호를 확인 해 주세요!\");\r\n");
      out.write("                     $(\"input[name='after_phone']\").focus();//포커스 이동\r\n");
      out.write("                  } else {\r\n");
      out.write("                     console.log(\"서버 전송\");\r\n");
      out.write("                     obj.url = \"./m_update\";\r\n");
      out.write("                     obj.data.mem_pw = $(\"input[name='userPw']\").val();\r\n");
      out.write("                     obj.data.mem_name = $(\r\n");
      out.write("                           \"input[name='after_userName']\").val();\r\n");
      out.write("                     obj.data.mem_gender = $(\r\n");
      out.write("                           \"input[name='gender']:checked\").val();\r\n");
      out.write("                     obj.data.mem_size = $(\"input[name='sizeview']\")\r\n");
      out.write("                           .val();\r\n");
      out.write("                     obj.data.mem_email = $(\"input[name='after_email']\")\r\n");
      out.write("                           .val()\r\n");
      out.write("                           + \"@\"\r\n");
      out.write("                           + $(\"input[name=after_emailview]\").val();\r\n");
      out.write("                     obj.data.mem_addr1 = $(\"input[name='addr1']\").val();\r\n");
      out.write("                     obj.data.mem_addr2 = $(\"input[name='addr2']\").val();\r\n");
      out.write("                     obj.data.mem_addr3 = $(\"input[name='addr3']\").val();\r\n");
      out.write("                     obj.data.mem_phone = $(\"input[name='after_phone']\")\r\n");
      out.write("                           .val();\r\n");
      out.write("                     obj.success = function(data) {\r\n");
      out.write("                        if (data.success == 1) {\r\n");
      out.write("                           alert(\"회원 정보 수정을 완료했습니다.\");\r\n");
      out.write("                           location.href = \"./mypage\";\r\n");
      out.write("                        } else {\r\n");
      out.write("                           alert(\"회원 정보 수정에 실패했습니다.\");\r\n");
      out.write("                        }\r\n");
      out.write("                     }\r\n");
      out.write("                     console.log(obj);\r\n");
      out.write("                     ajaxCall(obj);\r\n");
      out.write("                  }\r\n");
      out.write("               });\r\n");
      out.write("\r\n");
      out.write("   //전달 받은 오브젝트로 ajax 통신 실행\r\n");
      out.write("   function ajaxCall(obj) {\r\n");
      out.write("      $.ajax(obj);\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("   //주소 찾기 \r\n");
      out.write("   function sample4_execDaumPostcode() {\r\n");
      out.write("      new daum.Postcode(\r\n");
      out.write("            {\r\n");
      out.write("               oncomplete : function(data) {\r\n");
      out.write("                  // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\r\n");
      out.write("                  // 도로명 주소의 노출 규칙에 따라 주소를 조합한다.\r\n");
      out.write("                  // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("                  var fullRoadAddr = data.roadAddress; // 도로명 주소 변수\r\n");
      out.write("                  var extraRoadAddr = ''; // 도로명 조합형 주소 변수\r\n");
      out.write("\r\n");
      out.write("                  // 법정동명이 있을 경우 추가한다. (법정리는 제외)\r\n");
      out.write("                  // 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\r\n");
      out.write("                  if (data.bname !== '' && /[동|로|가]$/g.test(data.bname)) {\r\n");
      out.write("                     extraRoadAddr += data.bname;\r\n");
      out.write("                  }\r\n");
      out.write("                  // 건물명이 있고, 공동주택일 경우 추가한다.\r\n");
      out.write("                  if (data.buildingName !== '' && data.apartment === 'Y') {\r\n");
      out.write("                     extraRoadAddr += (extraRoadAddr !== '' ? ', '\r\n");
      out.write("                           + data.buildingName : data.buildingName);\r\n");
      out.write("                  }\r\n");
      out.write("                  // 도로명, 지번 조합형 주소가 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\r\n");
      out.write("                  if (extraRoadAddr !== '') {\r\n");
      out.write("                     extraRoadAddr = ' (' + extraRoadAddr + ')';\r\n");
      out.write("                  }\r\n");
      out.write("                  // 도로명, 지번 주소의 유무에 따라 해당 조합형 주소를 추가한다.\r\n");
      out.write("                  if (fullRoadAddr !== '') {\r\n");
      out.write("                     fullRoadAddr += extraRoadAddr;\r\n");
      out.write("                  }\r\n");
      out.write("\r\n");
      out.write("                  // 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("                  document.getElementById('sample4_postcode').value = data.zonecode; //5자리 새우편번호 사용\r\n");
      out.write("                  document.getElementById('sample4_roadAddress').value = fullRoadAddr;\r\n");
      out.write("                  document.getElementById('sample4_jibunAddress').value = data.jibunAddress;\r\n");
      out.write("\r\n");
      out.write("                  // 사용자가 '선택 안함'을 클릭한 경우, 예상 주소라는 표시를 해준다.\r\n");
      out.write("                  if (data.autoRoadAddress) {\r\n");
      out.write("                     //예상되는 도로명 주소에 조합형 주소를 추가한다.\r\n");
      out.write("                     var expRoadAddr = data.autoRoadAddress\r\n");
      out.write("                           + extraRoadAddr;\r\n");
      out.write("                     document.getElementById('guide').innerHTML = '(예상 도로명 주소 : '\r\n");
      out.write("                           + expRoadAddr + ')';\r\n");
      out.write("\r\n");
      out.write("                  } else if (data.autoJibunAddress) {\r\n");
      out.write("                     var expJibunAddr = data.autoJibunAddress;\r\n");
      out.write("                     document.getElementById('guide').innerHTML = '(예상 지번 주소 : '\r\n");
      out.write("                           + expJibunAddr + ')';\r\n");
      out.write("\r\n");
      out.write("                  } else {\r\n");
      out.write("                     document.getElementById('guide').innerHTML = '';\r\n");
      out.write("                  }\r\n");
      out.write("               }\r\n");
      out.write("            }).open();\r\n");
      out.write("   }\r\n");
      out.write("</script>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
