/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.30
 * Generated at: 2018-07-11 00:45:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class myproduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/FinalProjecthee/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/final/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/./mypage.jsp", Long.valueOf(1531269634201L));
    _jspx_dependants.put("/WEB-INF/views/././head.jsp", Long.valueOf(1531194371598L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1531192822154L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("     \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.1.0.min.js\"></script>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("\t#sel{\r\n");
      out.write("\t\tmargin-top: -1%;   \r\n");
      out.write("\t}\r\n");
      out.write("\t#tab{\r\n");
      out.write("\t\tmargin-left: 10%; \t\t\r\n");
      out.write("\t\tmargin-left: 0%;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t#tab table{\r\n");
      out.write("\t\twidth: 80%;\r\n");
      out.write("\t}\r\n");
      out.write("\t#buybtn{\r\n");
      out.write("\t\tmargin-left: 85.5%;  \r\n");
      out.write("\t\tmargin-top: 0%;      \r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\tbackground-color: white;\r\n");
      out.write("\t\tcolor: black;\r\n");
      out.write("\t\toutline: 0;\r\n");
      out.write("\t\tborder: 0;\r\n");
      out.write("\t\tfont-size: 15px;  \r\n");
      out.write("\t\ttext-decoration: none;\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t}\r\n");
      out.write("\t#buybtn:hover{\r\n");
      out.write("\t\tbackground-color: black;\r\n");
      out.write("\t\tcolor: white;\r\n");
      out.write("\t\toutline: 0;\r\n");
      out.write("\t\tborder: 0;\r\n");
      out.write("\t}\r\n");
      out.write("\t#buydel{\r\n");
      out.write("\t\tmargin-left: 85.5%;  \r\n");
      out.write("\t\tmargin-top: 15%;      \r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\tbackground-color: white;\r\n");
      out.write("\t\toutline: 0;\r\n");
      out.write("\t\tborder: 0;\r\n");
      out.write("\t\tfont-size: 15px;  \r\n");
      out.write("\t}\r\n");
      out.write("\t#buydel:hover {\r\n");
      out.write("\t\tbackground-color: black;\r\n");
      out.write("\t\tcolor: white;\r\n");
      out.write("\t\toutline: 0;\r\n");
      out.write("\t\tborder: 0;\r\n");
      out.write("\t}\r\n");
      out.write("\t#sel2{\r\n");
      out.write("\t\tcursor: pointer;\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t#tr1 tr{\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t}\r\n");
      out.write("\t#tr1 tr:hover {\r\n");
      out.write("\t\tbackground-color: #EAEAEA;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.pop-layer1 .pop-container1 {\r\n");
      out.write("\t  padding: 20px 25px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.pop-layer1 p.ctxt {\r\n");
      out.write("\t  color: #666;\r\n");
      out.write("\t  line-height: 25px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.pop-layer1 .btn-r {\r\n");
      out.write("\t  width: 100%;\r\n");
      out.write("\t  margin: 10px 0 20px;\r\n");
      out.write("\t  padding-top: 10px;\r\n");
      out.write("\t  border-top: 1px solid #DDD;\r\n");
      out.write("\t  text-align: right;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.pop-layer1 {\r\n");
      out.write("\t  display: none;\r\n");
      out.write("\t  position: absolute;\r\n");
      out.write("\t  top: 50%;\r\n");
      out.write("\t  left: 50%;\r\n");
      out.write("\t  width: 410px;\r\n");
      out.write("\t  height: auto;\r\n");
      out.write("\t  background-color: #fff;\r\n");
      out.write("\t  border: 5px solid black;\r\n");
      out.write("\t  z-index: 10;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.dim-layer1 {\r\n");
      out.write("\t  display: none;\r\n");
      out.write("\t  position: fixed;\r\n");
      out.write("\t  _position: absolute;\r\n");
      out.write("\t  top: 0;\r\n");
      out.write("\t  left: 0;\r\n");
      out.write("\t  width: 100%;\r\n");
      out.write("\t  height: 100%;\r\n");
      out.write("\t  z-index: 100;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.dim-layer1 .dimBg1 {\r\n");
      out.write("\t  position: absolute;\r\n");
      out.write("\t  top: 0;\r\n");
      out.write("\t  left: 0;\r\n");
      out.write("\t  width: 100%;\r\n");
      out.write("\t  height: 100%;\r\n");
      out.write("\t  background: #000;\r\n");
      out.write("\t  opacity: .5;\r\n");
      out.write("\t  filter: alpha(opacity=50);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.dim-layer1 .pop-layer1 {\r\n");
      out.write("\t  display: block;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\ta.btn-layerClose {\r\n");
      out.write("\t  display: inline-block;\r\n");
      out.write("\t  height: 25px;\r\n");
      out.write("\t  padding: 0 14px 0;\t  \r\n");
      out.write("\t  background-color: black;\r\n");
      out.write("\t  color: white;\r\n");
      out.write("\t  font-size: 13px;\r\n");
      out.write("\t  color: #fff;\r\n");
      out.write("\t  line-height: 25px;\r\n");
      out.write("\t  text-decoration: none;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\ta.btn-layerClose:hover {\r\n");
      out.write("\t  background-color: white;\r\n");
      out.write("\t  color: black;\r\n");
      out.write("\t}\r\n");
      out.write("\t#ok{\r\n");
      out.write("\t\tbackground-color: black;\r\n");
      out.write("\t\tcolor: white;\r\n");
      out.write("\t\tborder: 0;\r\n");
      out.write("\t\toutline: 0;\r\n");
      out.write("\t\tmargin-left: 80%;\r\n");
      out.write("\t\tmargin-top: -6%;\r\n");
      out.write("\t}\r\n");
      out.write("\t#ok:hover {\r\n");
      out.write("\t\tbackground-color: white;\r\n");
      out.write("\t\tcolor: black;\r\n");
      out.write("\t}\r\n");
      out.write("\t.btn-example1{\r\n");
      out.write("\t\tcolor: black;\r\n");
      out.write("\t\ttext-decoration: none;\r\n");
      out.write("\t}\r\n");
      out.write("\t.btn-example1:hover{\r\n");
      out.write("\t\tbackground-color: black;\r\n");
      out.write("\t\tcolor: white;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.1.0.min.js\"></script>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("\t#myname{\r\n");
      out.write("\t \tmargin-left: 5%;\t \t\r\n");
      out.write("\t}\r\n");
      out.write("\t#mymenu{\r\n");
      out.write("\t\tmargin-top: 2%;\r\n");
      out.write("\t\tborder-bottom: 1px solid black;\r\n");
      out.write("\t}\r\n");
      out.write("\t#mymenu a{\r\n");
      out.write("\t\tcolor: black;\r\n");
      out.write("\t\ttext-decoration: none;\t\r\n");
      out.write("\t\tmargin-left: 12%;\t\t\r\n");
      out.write("\t\tfont-size: large;\r\n");
      out.write("\t\tfont-style: inherit; \r\n");
      out.write("\t}\r\n");
      out.write("\t#mymenu a:hover{\r\n");
      out.write("\t\tbackground-color: black;\r\n");
      out.write("\t\tcolor: white;\r\n");
      out.write("\t}\r\n");
      out.write("\t#sel{\r\n");
      out.write("\t\tmargin-left: 85%; \r\n");
      out.write("\t\tmargin-top: -2%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t.pop-layer .pop-container {\r\n");
      out.write("\t  padding: 20px 25px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.pop-layer p.ctxt {\r\n");
      out.write("\t  color: #666;\r\n");
      out.write("\t  line-height: 25px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.pop-layer .btn-r {\r\n");
      out.write("\t  width: 100%;\r\n");
      out.write("\t  margin: 10px 0 20px;\r\n");
      out.write("\t  padding-top: 10px;\r\n");
      out.write("\t  border-top: 1px solid #DDD;\r\n");
      out.write("\t  text-align: right;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.pop-layer {\r\n");
      out.write("\t  display: none;\r\n");
      out.write("\t  position: absolute;\r\n");
      out.write("\t  top: 50%;\r\n");
      out.write("\t  left: 50%;\r\n");
      out.write("\t  width: 410px;\r\n");
      out.write("\t  height: auto;\r\n");
      out.write("\t  background-color: #fff;\r\n");
      out.write("\t  border: 5px solid black;\r\n");
      out.write("\t  z-index: 10;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.dim-layer {\r\n");
      out.write("\t  display: none;\r\n");
      out.write("\t  position: fixed;\r\n");
      out.write("\t  _position: absolute;\r\n");
      out.write("\t  top: 0;\r\n");
      out.write("\t  left: 0;\r\n");
      out.write("\t  width: 100%;\r\n");
      out.write("\t  height: 100%;\r\n");
      out.write("\t  z-index: 100;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.dim-layer .dimBg {\r\n");
      out.write("\t  position: absolute;\r\n");
      out.write("\t  top: 0;\r\n");
      out.write("\t  left: 0;\r\n");
      out.write("\t  width: 100%;\r\n");
      out.write("\t  height: 100%;\r\n");
      out.write("\t  background: #000;\r\n");
      out.write("\t  opacity: .5;\r\n");
      out.write("\t  filter: alpha(opacity=50);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.dim-layer .pop-layer {\r\n");
      out.write("\t  display: block;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\ta.btn-layerClose {\r\n");
      out.write("\t  display: inline-block;\r\n");
      out.write("\t  height: 25px;\r\n");
      out.write("\t  padding: 0 14px 0;\t  \r\n");
      out.write("\t  background-color: black;\r\n");
      out.write("\t  color: white;\r\n");
      out.write("\t  font-size: 13px;\r\n");
      out.write("\t  color: #fff;\r\n");
      out.write("\t  line-height: 25px;\r\n");
      out.write("\t  text-decoration: none;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\ta.btn-layerClose:hover {\r\n");
      out.write("\t  background-color: white;\r\n");
      out.write("\t  color: black;\r\n");
      out.write("\t}\r\n");
      out.write("\t#shopname{\r\n");
      out.write("\t\tmargin-left: 28%;\r\n");
      out.write("\t}\r\n");
      out.write("\t#shop_idx{\r\n");
      out.write("\t\t/* display: none; */\r\n");
      out.write("\t}\r\n");
      out.write("\t#shop\r\n");
      out.write("\t.pop-conts h4{\r\n");
      out.write("\t\tmargin-left: 27%; \r\n");
      out.write("\t}\r\n");
      out.write("\t.btn-example{\r\n");
      out.write("\t\tbackground-color: black;\r\n");
      out.write("\t\tcolor: white;\r\n");
      out.write("\t\ttext-decoration: none;\r\n");
      out.write("\t}\r\n");
      out.write("\t.btn-example:hover{\r\n");
      out.write("\t\tbackground-color: white;\r\n");
      out.write("\t\tcolor: black;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery-3.1.0.min.js\"></script>\r\n");
      out.write("\t<title>Insert title here</title>\r\n");
      out.write("\t<style>\t\r\n");
      out.write("\t\t#back{\r\n");
      out.write("\t\t\tbackground-color: black;\r\n");
      out.write("\t\t\tmargin: -1%;  \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t#div1{\r\n");
      out.write("\t\t\twidth: 50%;\r\n");
      out.write("\t\t\theight: 20%;\r\n");
      out.write("\t\t\tmargin-left: 72%;\r\n");
      out.write("\t\t\tmargin-top: 1%;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t#div1 a{\r\n");
      out.write("\t\t\tposition: static;\t\t\t\r\n");
      out.write("\t\t\tcursor: pointer;\r\n");
      out.write("\t\t\tcolor: black;\r\n");
      out.write("\t\t\tfont-size: 20px;\r\n");
      out.write("\t\t\ttext-decoration: none;\t\r\n");
      out.write("\t\t\ttext-align:center;\r\n");
      out.write("\t\t\tcolor: white;\t\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#div1 a:hover {\r\n");
      out.write("\t\t\tbackground-color: white;\t\t\t\r\n");
      out.write("\t\t\tfont-size: 20px;\r\n");
      out.write("\t\t\tcolor: black;\r\n");
      out.write("\t\t\ttext-decoration: none;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t#div3{\r\n");
      out.write("\t\t\twidth: 50%;\r\n");
      out.write("\t\t\theight: 20%; \r\n");
      out.write("\t\t\tmargin-left: 85%;\r\n");
      out.write("\t\t\tmargin-top: 1%;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#div3 a{\r\n");
      out.write("\t\t\tposition: static;\t\t\t\r\n");
      out.write("\t\t\tcursor: pointer;\r\n");
      out.write("\t\t\tcolor: black;\r\n");
      out.write("\t\t\tfont-size: 20px;\r\n");
      out.write("\t\t\ttext-decoration: none;\t\r\n");
      out.write("\t\t\ttext-align:center;\r\n");
      out.write("\t\t\tcolor: white;\t\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#div3 a:hover {\r\n");
      out.write("\t\t\tbackground-color: white;\t\t\t\r\n");
      out.write("\t\t\tfont-size: 20px;\r\n");
      out.write("\t\t\tcolor: black;\r\n");
      out.write("\t\t\ttext-decoration: none;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t#select{\r\n");
      out.write("\t\t\tmargin-top: 0.5%;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t#mainimg{\r\n");
      out.write("\t\t\tposition: absolute;\r\n");
      out.write("\t\t\tcolor: white;\r\n");
      out.write("\t\t\tmargin-left: 1%;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#div2{\r\n");
      out.write("\t\t\tmargin-left: 15%;\t\t\t\r\n");
      out.write("\t\t\ttop: 1%;\r\n");
      out.write("\t\t\tborder-bottom: solid 1px black;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#div2 a{\r\n");
      out.write("\t\t\tposition: static;\t\t\t\r\n");
      out.write("\t\t\tcursor: pointer;\r\n");
      out.write("\t\t\tcolor: white;\r\n");
      out.write("\t\t\tfont-size: 20px;\r\n");
      out.write("\t\t\ttext-decoration: none;\t\r\n");
      out.write("\t\t\ttext-align:center;\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#div2 a:hover {\r\n");
      out.write("\t\t\tbackground-color: white;\r\n");
      out.write("\t\t\tcolor: black;\t\t\t\r\n");
      out.write("\t\t\tfont-size: 20px;\r\n");
      out.write("\t\t\ttext-decoration: none;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#div2 p{\r\n");
      out.write("\t\t\tmargin-left: 12%;\r\n");
      out.write("\t\t\tposition: absolute;\r\n");
      out.write("\t\t\tmargin-top: -1.5%;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#mainimg{\r\n");
      out.write("\t\t\tcursor: pointer;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tbutton{\r\n");
      out.write("\t\t\tcursor: pointer;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#selbtn{\r\n");
      out.write("\t\t\tborder: 0;\r\n");
      out.write("\t\t\tbackground-color: black;\r\n");
      out.write("\t\t\tcolor: white;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#selbtn:hover {\r\n");
      out.write("\t\t\tbackground-color: white;\r\n");
      out.write("\t\t\tcolor: black;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"overflow-x:hidden; overflow-y:auto;\">\r\n");
      out.write("\t<div id=\"back\">\r\n");
      out.write("\t<!-- img id=\"mainimg\"  src=\"resources/img.jpg\" width=\"200px;\" onclick=\"location.href='./'\"> -->\r\n");
      out.write("\t<h2 id=\"mainimg\" onclick=\"location.href='./'\"> 슈마니커</h2>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"div2\">\r\n");
      out.write("\t\t<a href=\"category\">카테고리</a>\r\n");
      out.write("\t\t<a href=\"speller\">맞춤 상품</a>\t\t\t\r\n");
      out.write("\t\t<p><input id=\"select\" type=\"text\"/><button id=\"selbtn\">검색</button></p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("/* \t$(\"#select\").click(function() {\r\n");
      out.write("\t\tif($(\"#selbtn\").css(\"diplay\")==\"none\"){\r\n");
      out.write("\t\t\t$(\"#selbtn\").css(\"diplay\", \"block\");\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$(\"#selbtn\").css(\"diplay\")==\"none\");\r\n");
      out.write("\t\t};\r\n");
      out.write("\t});\r\n");
      out.write("\t */\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"dim-layer\">\r\n");
      out.write("    <div class=\"dimBg\"></div>\r\n");
      out.write("    <div id=\"layer2\" class=\"pop-layer\">\r\n");
      out.write("        <div class=\"pop-container\">\r\n");
      out.write("            <div class=\"pop-conts\">\r\n");
      out.write("                <!--content //-->\r\n");
      out.write("                <h4 class=\"ctxt mb20\">상점 이름을 입력 하세요</h4>\r\n");
      out.write("                   <input id=\"shopname\" type=\"text\">\r\n");
      out.write("\t\t\t\t   <input type =\"button\" value=\"중복확인\" onclick=\"shopOverlay()\"/>\r\n");
      out.write("                </p>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"btn-r\">\r\n");
      out.write("                    <a href=\"#\" class=\"btn-layerClose\">확인</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!--// content-->\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"mymenu\">\r\n");
      out.write("\t\t<a href=\"./myproduct\">상품등록</a>\r\n");
      out.write("\t\t<a href=\"./mybuy\">구매내역</a>\r\n");
      out.write("\t\t<a href=\"./mycartCall\">찜목록</a>\r\n");
      out.write("\t\t<a href=\"./myreview\">상점후기 </a>\r\n");
      out.write("\t\t<a href=\"./myinfo\">개인정보 수정</a>\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\tif('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.shopState eq 1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'){\r\n");
      out.write("\t\t\tgetShopInfo();\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$('.btn-example').click(function(){\r\n");
      out.write("\t    var $href = $(this).attr('href');\r\n");
      out.write("\t    layer_popup($href);\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction layer_popup(el){\r\n");
      out.write("\r\n");
      out.write("\t    var $el = $(el);        //레이어의 id를 $el 변수에 저장\r\n");
      out.write("\t    var isDim = $el.prev().hasClass('dimBg');   //dimmed 레이어를 감지하기 위한 boolean 변수\r\n");
      out.write("\t\r\n");
      out.write("\t    isDim ? $('.dim-layer').fadeIn() : $el.fadeIn();\r\n");
      out.write("\t\r\n");
      out.write("\t    var $elWidth = ~~($el.outerWidth()),\r\n");
      out.write("\t        $elHeight = ~~($el.outerHeight()),\r\n");
      out.write("\t        docWidth = $(document).width(),\r\n");
      out.write("\t        docHeight = $(document).height();\r\n");
      out.write("\t\r\n");
      out.write("\t    // 화면의 중앙에 레이어를 띄운다.\r\n");
      out.write("\t    if ($elHeight < docHeight || $elWidth < docWidth) {\r\n");
      out.write("\t        $el.css({\r\n");
      out.write("\t            marginTop: -$elHeight /2,\r\n");
      out.write("\t            marginLeft: -$elWidth/2\r\n");
      out.write("\t        })\r\n");
      out.write("\t    } else {\r\n");
      out.write("\t        $el.css({top: 0, left: 0});\r\n");
      out.write("\t    }\r\n");
      out.write("\t\r\n");
      out.write("\t    $el.find('a.btn-layerClose').click(function(){\r\n");
      out.write("\t    \tif($('#shopname').val() != '' && overChk == true){\r\n");
      out.write("\t    \t\tisDim ? $('.dim-layer').fadeOut() : $el.fadeOut(); // 닫기 버튼을 클릭하면 레이어가 닫힌다.\t\r\n");
      out.write("\t    \t}\t        \r\n");
      out.write("\t        return false;\r\n");
      out.write("\t    });\r\n");
      out.write("\t\r\n");
      out.write("\t    $('.layer .dimBg').click(function(){\r\n");
      out.write("\t        $('.dim-layer').fadeOut();\r\n");
      out.write("\t        return false;\r\n");
      out.write("\t    });\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\t//상점이름 입력 후 확인 클릭시 값 INSERT\r\n");
      out.write("\t$('.btn-layerClose').click(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif($('#shopname').val() == ''){\r\n");
      out.write("\t\t\talert('상점명은 반드시 기입하셔야 합니다. 다시 입력하여 주세요');\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tif (!overChk) {\r\n");
      out.write("\t\t\t\talert(\"상점명 중복 체크를 실행 해 주세요!\");\r\n");
      out.write("\t\t\t\t$('#shopname').focus();//포커스 이동\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse if($('#shopname').val() != ''){\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\ttype:\"GET\",\r\n");
      out.write("\t\t\t\t\turl:\"./setShopName\",\r\n");
      out.write("\t\t\t\t\tdata:{\r\n");
      out.write("\t\t\t\t\t\tshopName : $('#shopname').val() ,\r\n");
      out.write("\t\t\t\t\t\tid : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tdataType:\"JSON\",\r\n");
      out.write("\t\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\t\tif(data.success>0){\r\n");
      out.write("\t\t\t\t\t\t\tconsole.log('insert 성공');\r\n");
      out.write("\t\t\t\t\t\t\tupShopState();\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror : function(err){\r\n");
      out.write("\t\t\t\t\t\tconsole.log(err);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}); \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tvar overChk = false;//중복체크 값\r\n");
      out.write("\t//상점명 중복 확인\r\n");
      out.write("\tfunction shopOverlay(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"GET\",\r\n");
      out.write("\t\t\turl:\"./shopOverlay\",\r\n");
      out.write("\t\t\tdata:{\r\n");
      out.write("\t\t\t\tshopName : $('#shopname').val()\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdataType:\"JSON\",\r\n");
      out.write("\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\tif(data.overlay){\r\n");
      out.write("\t\t\t\t\talert('이미 사용중인 상점명입니다. 다른 상점명을 입력해 주세요');\r\n");
      out.write("\t\t\t\t\t$('#shopname').val('');\r\n");
      out.write("\t\t\t\t\t$('#shopname').focus();\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\talert(\"사용 가능한 상점명 입니다.\");\r\n");
      out.write("\t\t\t\t\t$('#shopname').css('color', 'green');\r\n");
      out.write("\t\t\t\t\toverChk = true;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(err){\r\n");
      out.write("\t\t\t\tconsole.log(err);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//상점개설 여부 상태값 UPDATE\r\n");
      out.write("\tfunction upShopState(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"GET\",\r\n");
      out.write("\t\t\turl:\"./upShopState\",\r\n");
      out.write("\t\t\tdata:{\r\n");
      out.write("\t\t\t\tidx : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdataType:\"JSON\",\r\n");
      out.write("\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\tif(data.success > 0){\r\n");
      out.write("\t\t\t\t\tconsole.log('상태값 수정완료');\r\n");
      out.write("\t\t\t\t\tgetMemShopState();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(err){\r\n");
      out.write("\t\t\t\tconsole.log(err);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}); \r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//상점개설상태 값 얻기\r\n");
      out.write("\tfunction getMemShopState(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"GET\",\r\n");
      out.write("\t\t\turl:\"./getMemShopState\",\r\n");
      out.write("\t\t\tdata:{\r\n");
      out.write("\t\t\t\tid : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdataType:\"JSON\",\r\n");
      out.write("\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\tif(data.result != null){\r\n");
      out.write("\t\t\t\t\tconsole.log(data.result);\r\n");
      out.write("\t\t\t\t\tconsole.log('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.shopState}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("');\r\n");
      out.write("\t\t\t\t\talert('상점이 개설되었습니다.');\r\n");
      out.write("\t\t\t\t\tlocation.href = \"./mypage?id='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(err){\r\n");
      out.write("\t\t\t\tconsole.log(err);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//상점정보 출력\r\n");
      out.write("\tfunction getShopInfo(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"GET\",\r\n");
      out.write("\t\t\turl:\"./getShopInfo\",\r\n");
      out.write("\t\t\tdata:{\r\n");
      out.write("\t\t\t\tid : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdataType:\"JSON\",\r\n");
      out.write("\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\tif(data.dto != null){\r\n");
      out.write("\t\t\t\t\t$('#shopInfo').append(\r\n");
      out.write("\t\t\t\t\t\"<h3>상점 이름 =\" + data.dto.shop_name + \"<br/>\" +\r\n");
      out.write("\t\t\t\t\t\"상품판매 개수 = \" + data.dto.shop_sellcount + \"<br/>\" +\r\n");
      out.write("\t\t\t\t\t\"상점 개설 날짜 = \" + data.dto.shop_date + \"<br/> </h3>\" +\r\n");
      out.write("\t\t\t\t\t\"<h3>상점 주인=<div id='mem_id'>\"+data.dto.mem_id+\"</div></h3>\"+\r\n");
      out.write("\t\t\t\t\t\"<div id='shop_idx'>\" + \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.shopIdx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"+\"</div>\"\r\n");
      out.write("\t\t\t\t\t);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(err){\r\n");
      out.write("\t\t\t\tconsole.log(err);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<h3>상품리스트</h3>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<select id=\"sel\">\r\n");
      out.write("\t\t\t<option>최신등록순</option>\r\n");
      out.write("\t\t\t<option>오래된순</option>\r\n");
      out.write("\t\t</select>\t\r\n");
      out.write("\t</div>  \t<!-- <a > -->\r\n");
      out.write("\t<button id=\"buybtn\" onclick='location.href = \"./regProduct\"'>상품등록</button>\r\n");
      out.write("\t<button id=\"buydel\">상품삭제 </button>\r\n");
      out.write("\t<div id=tab>\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<thead>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t\t<th>번호</th>\r\n");
      out.write("\t\t\t\t\t<th>상품정보</th>\r\n");
      out.write("\t\t\t\t\t<th>등록날짜</th>\r\n");
      out.write("\t\t\t\t\t<th>상품상태</th>\r\n");
      out.write("\t\t\t\t\t<th>상태 변경</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t\t<tbody  id=\"tr1\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th><input type=\"checkbox\"/></th>\r\n");
      out.write("\t\t\t\t\t<th>2번</th>\r\n");
      out.write("\t\t\t\t\t<th>아디다스</th>\r\n");
      out.write("\t\t\t\t\t<th>2018-06-03</th>\r\n");
      out.write("\t\t\t\t\t<th>판매중</th>\r\n");
      out.write("\t\t\t\t\t<th><a href=\"#layer3\" class=\"btn-example1\">변경</a></th> \r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th><input type=\"checkbox\"/></th>\r\n");
      out.write("\t\t\t\t\t<th>3번</th>\r\n");
      out.write("\t\t\t\t\t<th>리복</th>\r\n");
      out.write("\t\t\t\t\t<th>2018-05-03</th>\r\n");
      out.write("\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t<select>\r\n");
      out.write("\t\t\t\t\t\t\t<option>판매중</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>판매완료</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th><input type=\"checkbox\"/></th>\r\n");
      out.write("\t\t\t\t\t<th>3번</th>\r\n");
      out.write("\t\t\t\t\t<th>리복</th>\r\n");
      out.write("\t\t\t\t\t<th>2018-05-03</th>\r\n");
      out.write("\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t<select>\r\n");
      out.write("\t\t\t\t\t\t\t<option>판매중</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>판매완료</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th><input type=\"checkbox\"/></th>\r\n");
      out.write("\t\t\t\t\t<th>3번</th>\r\n");
      out.write("\t\t\t\t\t<th>리복</th>\r\n");
      out.write("\t\t\t\t\t<th>2018-05-03</th>\r\n");
      out.write("\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t<select>\r\n");
      out.write("\t\t\t\t\t\t\t<option>판매중</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>판매완료</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"dim-layer1\">\r\n");
      out.write("    <div class=\"dimBg1\"></div>\r\n");
      out.write("    <div id=\"layer3\" class=\"pop-layer1\">\r\n");
      out.write("        <div class=\"pop-container1\">\r\n");
      out.write("            <div class=\"pop-conts\">\r\n");
      out.write("                <!--content //-->\r\n");
      out.write("                <h4 class=\"ctxt mb20\">구매자의 아이디를 입력하세요</h4>\r\n");
      out.write("                   <input style=\"height: 15px\" id=\"shopname\" type=\"text\"><br>\r\n");
      out.write("                   <button id=\"ok\">확인</button>\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("\r\n");
      out.write("                <div class=\"btn-r\">\r\n");
      out.write("                    <a href=\"#\" class=\"btn-layerClose\">판매 완료</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!--// content-->\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$('.btn-example1').click(function(){\r\n");
      out.write("    var $href = $(this).attr('href');\r\n");
      out.write("    layer_popup($href);\r\n");
      out.write("});\r\n");
      out.write("function layer_popup(el){\r\n");
      out.write("\r\n");
      out.write("    var $el = $(el);        //레이어의 id를 $el 변수에 저장\r\n");
      out.write("    var isDim = $el.prev().hasClass('dimBg1');   //dimmed 레이어를 감지하기 위한 boolean 변수\r\n");
      out.write("\r\n");
      out.write("    isDim ? $('.dim-layer1').fadeIn() : $el.fadeIn();\r\n");
      out.write("\r\n");
      out.write("    var $elWidth = ~~($el.outerWidth()),\r\n");
      out.write("        $elHeight = ~~($el.outerHeight()),\r\n");
      out.write("        docWidth = $(document).width(),\r\n");
      out.write("        docHeight = $(document).height();\r\n");
      out.write("\r\n");
      out.write("    // 화면의 중앙에 레이어를 띄운다.\r\n");
      out.write("    if ($elHeight < docHeight || $elWidth < docWidth) {\r\n");
      out.write("        $el.css({\r\n");
      out.write("            marginTop: -$elHeight /2,\r\n");
      out.write("            marginLeft: -$elWidth/2\r\n");
      out.write("        })\r\n");
      out.write("    } else {\r\n");
      out.write("        $el.css({top: 0, left: 0});\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    $el.find('a.btn-layerClose').click(function(){\r\n");
      out.write("        isDim ? $('.dim-layer1').fadeOut() : $el.fadeOut(); // 닫기 버튼을 클릭하면 레이어가 닫힌다.\r\n");
      out.write("        return false;\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    $('.layer .dimBg1').click(function(){\r\n");
      out.write("        $('.dim-layer1').fadeOut();\r\n");
      out.write("        return false;\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/././head.jsp(122,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginId == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t<div id=\"div3\">\t\t\r\n");
          out.write("\t\t<a href=\"./joinForm\">회원가입</a>\r\n");
          out.write("\t\t<a href=\"./index\">로그인</a>\r\n");
          out.write("\t\t<a href=\"#\">공지사항</a><br/>\r\n");
          out.write("\t</div>\t\r\n");
          out.write("\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/././head.jsp(130,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginId != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t<div id=\"div1\">\t\t\r\n");
          out.write("\t\t<a href=\"./logout\">로그아웃</a>\r\n");
          out.write("\t\t<a href=\"./mypage?id='");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("'\">마이페이지</a>\r\n");
          out.write("\t\t<a href=\"#\">공지사항</a>\r\n");
          out.write("\t\t<a href=\"#\">요청게시판</a>\r\n");
          out.write("\t\t<a href=\"#\">찜목록</a><br/>\r\n");
          out.write("\t</div>\t\r\n");
          out.write("\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/././head.jsp(140,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginId == 'admin'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t<div id=\"div1\">\t\t\r\n");
          out.write("\t\t<a href=\"adminpage\">관리자 페이지</a>\r\n");
          out.write("\t\t<a href=\"#\">로그아웃</a>\r\n");
          out.write("\t\t<a href=\"#\">마이페이지</a>\r\n");
          out.write("\t\t<a href=\"#\">공지사항</a>\r\n");
          out.write("\t\t<a href=\"#\">요청게시판</a>\r\n");
          out.write("\t\t<a href=\"#\">찜목록</a><br/>\r\n");
          out.write("\t</div>\t\r\n");
          out.write("\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /WEB-INF/views/./mypage.jsp(130,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.shopState eq 0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t<div id=\"myname\">\r\n");
          out.write("\t\t\t<h2 align=\"center\">상점이 없습니다. 상점을 개설 하여 주세요</h2>\r\n");
          out.write("\t\t\t<h4 align=\"center\"><a href=\"#layer2\" class=\"btn-example\">상점개설</a></h4>\r\n");
          out.write("\t\t</div>\r\n");
          out.write("\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent(null);
      // /WEB-INF/views/./mypage.jsp(137,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.shopState eq 1 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t<div id=\"shopInfo\"></div>\r\n");
          out.write("\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/myproduct.jsp(189,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/myproduct.jsp(189,5) '${product}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${product}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t<th><input type=\"checkbox\"/></th>\r\n");
            out.write("\t\t\t\t\t\t\t<th>1번</th>\r\n");
            out.write("\t\t\t\t\t\t\t<th>나이키</th>\r\n");
            out.write("\t\t\t\t\t\t\t<th>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pro.xxx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</th>\r\n");
            out.write("\t\t\t\t\t\t\t<th>\r\n");
            out.write("\t\t\t\t\t\t\t\t<select id=\"sel2\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<option selected=\"selected\">판매중</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<option onclick=\"location.href='#layer3'\" class=\"btn-example1\">판매완료</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t</select>\r\n");
            out.write("\t\t\t\t\t\t\t</th>\r\n");
            out.write("\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
