/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.30
 * Generated at: 2018-07-18 01:58:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class myreview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/FinalProjecthee/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/final/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/./mypage.jsp", Long.valueOf(1531877802388L));
    _jspx_dependants.put("/WEB-INF/views/././head.jsp", Long.valueOf(1531877613466L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1531184863091L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("      \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.1.0.min.js\"></script>\r\n");
      out.write("<script src=\"resources/jquery-1.11.3.min.js\"></script>\r\n");
      out.write("<script src=\"resources/star.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<title>슈마니커~ ^^</title>\r\n");
      out.write("<style>\r\n");
      out.write(".star-input>.input,\r\n");
      out.write(".star-input>.input>label:hover,\r\n");
      out.write(".star-input>.input>input:focus+label,\r\n");
      out.write(".star-input>.input>input:checked+label{display: inline-block;vertical-align:middle;background:url('resources/grade_img.png')no-repeat;}\r\n");
      out.write(".star-input{display:inline-block; white-space:nowrap;width:225px;height:40px;padding:25px;line-height:30px;}\r\n");
      out.write(".star-input>.input{display:inline-block;width:150px;background-size:150px;height:28px;white-space:nowrap;overflow:hidden;position: relative;}\r\n");
      out.write(".star-input>.input>input{position:absolute;width:1px;height:1px;opacity:0;}\r\n");
      out.write(".star-input>.input.focus{outline:1px dotted #ddd;}\r\n");
      out.write(".star-input>.input>label{width:30px;height:0;padding:28px 0 0 0;overflow: hidden;float:left;cursor: pointer;position: absolute;top: 0;left: 0;}\r\n");
      out.write(".star-input>.input>label:hover,\r\n");
      out.write(".star-input>.input>input:focus+label,\r\n");
      out.write(".star-input>.input>input:checked+label{background-size: 150px;background-position: 0 bottom;}\r\n");
      out.write(".star-input>.input>label:hover{background-image: none;}\r\n");
      out.write(".star-input>.input>label[for=\"1\"]{width:30px;z-index:5;}\r\n");
      out.write(".star-input>.input>label[for=\"2\"]{width:60px;z-index:4;}\r\n");
      out.write(".star-input>.input>label[for=\"3\"]{width:90px;z-index:3;}\r\n");
      out.write(".star-input>.input>label[for=\"4\"]{width:120px;z-index:2;}\r\n");
      out.write(".star-input>.input>label[for=\"5\"]{width:150px;z-index:1;}\r\n");
      out.write(".star-input>output{display:inline-block;width:60px; font-size:18px;text-align:right; vertical-align:middle;}\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("   #tab{\r\n");
      out.write("      margin-left: 5%; \r\n");
      out.write("      margin-top: 1%;\r\n");
      out.write("   }\r\n");
      out.write("   #tab table{\r\n");
      out.write("      width: 80%;\r\n");
      out.write("   } \r\n");
      out.write("   #myReview tr{\r\n");
      out.write("      cursor: pointer;\r\n");
      out.write("   }\r\n");
      out.write("   #myReview tr:hover {\r\n");
      out.write("      background-color: #EAEAEA;\r\n");
      out.write("   }\r\n");
      out.write("   /* #reviewDel{\r\n");
      out.write("      margin-left: 85.5%;  \r\n");
      out.write("      margin-top: 15%;      \r\n");
      out.write("      position: absolute;\r\n");
      out.write("      background-color: white;\r\n");
      out.write("      outline: 0;\r\n");
      out.write("      border: 0;\r\n");
      out.write("      font-size: 15px;  \r\n");
      out.write("   }\r\n");
      out.write("   #reviewDel:hover {\r\n");
      out.write("      background-color: black;\r\n");
      out.write("      color: white;\r\n");
      out.write("      outline: 0;\r\n");
      out.write("      border: 0;\r\n");
      out.write("   } */\r\n");
      out.write("   #rev1{\r\n");
      out.write("      margin-left: 20%; \r\n");
      out.write("      word-spacing: 10px; \r\n");
      out.write("   }\r\n");
      out.write("   #sreply_content{\r\n");
      out.write("      width: 50%;\r\n");
      out.write("   }\r\n");
      out.write("   #selrev{\r\n");
      out.write("      width: 5%;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   #reviewWrite{\r\n");
      out.write("      margin-left: 70%;  \r\n");
      out.write("      margin-top: 0%;      \r\n");
      out.write("      position: absolute;\r\n");
      out.write("      background-color: white;\r\n");
      out.write("      outline: 0;\r\n");
      out.write("      border: 0;\r\n");
      out.write("      font-size: 15px;  \r\n");
      out.write("   }\r\n");
      out.write("   #reviewWrite:hover{\r\n");
      out.write("      background-color: black;\r\n");
      out.write("      color: white;\r\n");
      out.write("      outline: 0;\r\n");
      out.write("      border: 0;\r\n");
      out.write("   }\r\n");
      out.write("   #myReview{\r\n");
      out.write("      text-align: center;\r\n");
      out.write("   }\r\n");
      out.write("   .reviewdel{\r\n");
      out.write("      border: none;\r\n");
      out.write("      background: transparent;\r\n");
      out.write("\r\n");
      out.write("   }\r\n");
      out.write("   #reviewcontent{\r\n");
      out.write("      border : none;\r\n");
      out.write("   }\r\n");
      out.write("   .reviewupdate{\r\n");
      out.write("   display:none;\r\n");
      out.write("   }\r\n");
      out.write("   #starRateup{\r\n");
      out.write("   display:none;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.1.0.min.js\"></script>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("\t#myname{\r\n");
      out.write("\t \tmargin-left: 5%;\t \t\r\n");
      out.write("\t}\r\n");
      out.write("\t#mymenu{\r\n");
      out.write("\t\tmargin-top: 2%;\r\n");
      out.write("\t\tborder-bottom: 1px solid black;\r\n");
      out.write("\t}\r\n");
      out.write("\t#mymenu a{\r\n");
      out.write("\t\tcolor: black;\r\n");
      out.write("\t\ttext-decoration: none;\t\r\n");
      out.write("\t\tmargin-left: 12%;\t\t\r\n");
      out.write("\t\tfont-size: large;\r\n");
      out.write("\t\tfont-style: inherit; \r\n");
      out.write("\t}\r\n");
      out.write("\t#mymenu a:hover{\r\n");
      out.write("\t\tbackground-color: black;\r\n");
      out.write("\t\tcolor: white;\r\n");
      out.write("\t}\r\n");
      out.write("\t#sel{\r\n");
      out.write("\t\tmargin-left: 85%; \r\n");
      out.write("\t\tmargin-top: -2%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t.pop-layer .pop-container {\r\n");
      out.write("\t  padding: 20px 25px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.pop-layer p.ctxt {\r\n");
      out.write("\t  color: #666;\r\n");
      out.write("\t  line-height: 25px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.pop-layer .btn-r {\r\n");
      out.write("\t  width: 100%;\r\n");
      out.write("\t  margin: 10px 0 20px;\r\n");
      out.write("\t  padding-top: 10px;\r\n");
      out.write("\t  border-top: 1px solid #DDD;\r\n");
      out.write("\t  text-align: right;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.pop-layer {\r\n");
      out.write("\t  display: none;\r\n");
      out.write("\t  position: absolute;\r\n");
      out.write("\t  top: 50%;\r\n");
      out.write("\t  left: 50%;\r\n");
      out.write("\t  width: 410px;\r\n");
      out.write("\t  height: auto;\r\n");
      out.write("\t  background-color: #fff;\r\n");
      out.write("\t  border: 5px solid black;\r\n");
      out.write("\t  z-index: 10;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.dim-layer {\r\n");
      out.write("\t  display: none;\r\n");
      out.write("\t  position: fixed;\r\n");
      out.write("\t  _position: absolute;\r\n");
      out.write("\t  top: 0;\r\n");
      out.write("\t  left: 0;\r\n");
      out.write("\t  width: 100%;\r\n");
      out.write("\t  height: 100%;\r\n");
      out.write("\t  z-index: 100;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.dim-layer .dimBg {\r\n");
      out.write("\t  position: absolute;\r\n");
      out.write("\t  top: 0;\r\n");
      out.write("\t  left: 0;\r\n");
      out.write("\t  width: 100%;\r\n");
      out.write("\t  height: 100%;\r\n");
      out.write("\t  background: #000;\r\n");
      out.write("\t  opacity: .5;\r\n");
      out.write("\t  filter: alpha(opacity=50);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.dim-layer .pop-layer {\r\n");
      out.write("\t  display: block;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\ta.btn-layerClose {\r\n");
      out.write("\t  display: inline-block;\r\n");
      out.write("\t  height: 25px;\r\n");
      out.write("\t  padding: 0 14px 0;\t  \r\n");
      out.write("\t  background-color: black;\r\n");
      out.write("\t  color: white;\r\n");
      out.write("\t  font-size: 13px;\r\n");
      out.write("\t  color: #fff;\r\n");
      out.write("\t  line-height: 25px;\r\n");
      out.write("\t  text-decoration: none;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\ta.btn-layerClose:hover {\r\n");
      out.write("\t  background-color: white;\r\n");
      out.write("\t  color: black;\r\n");
      out.write("\t}\r\n");
      out.write("\t#shopname{\r\n");
      out.write("\t\tmargin-left: 28%;\r\n");
      out.write("\t}\r\n");
      out.write("\t#shop_idx{\r\n");
      out.write("\t\t/* display: none; */\r\n");
      out.write("\t}\r\n");
      out.write("\t#shop\r\n");
      out.write("\t.pop-conts h4{\r\n");
      out.write("\t\tmargin-left: 27%; \r\n");
      out.write("\t}\r\n");
      out.write("\t.btn-example{\r\n");
      out.write("\t\tbackground-color: black;\r\n");
      out.write("\t\tcolor: white;\r\n");
      out.write("\t\ttext-decoration: none;\r\n");
      out.write("\t}\r\n");
      out.write("\t.btn-example:hover{\r\n");
      out.write("\t\tbackground-color: white;\r\n");
      out.write("\t\tcolor: black;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery-3.1.0.min.js\"></script>\r\n");
      out.write("\t<title>Insert title here</title>\r\n");
      out.write("\t<style>\t\r\n");
      out.write("\t\t#back{\r\n");
      out.write("\t\t\tbackground-color: black;\r\n");
      out.write("\t\t\tmargin: -1%;  \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t#div1{\r\n");
      out.write("\t\t\twidth: 50%;\r\n");
      out.write("\t\t\theight: 20%;\r\n");
      out.write("\t\t\tmargin-left: 72%;\r\n");
      out.write("\t\t\tmargin-top: 1%;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t#div1 a{\r\n");
      out.write("\t\t\tposition: static;\t\t\t\r\n");
      out.write("\t\t\tcursor: pointer;\r\n");
      out.write("\t\t\tcolor: black;\r\n");
      out.write("\t\t\tfont-size: 20px;\r\n");
      out.write("\t\t\ttext-decoration: none;\t\r\n");
      out.write("\t\t\ttext-align:center;\r\n");
      out.write("\t\t\tcolor: white;\t\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#div1 a:hover {\r\n");
      out.write("\t\t\tbackground-color: white;\t\t\t\r\n");
      out.write("\t\t\tfont-size: 20px;\r\n");
      out.write("\t\t\tcolor: black;\r\n");
      out.write("\t\t\ttext-decoration: none;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t#div3{\r\n");
      out.write("\t\t\twidth: 50%;\r\n");
      out.write("\t\t\theight: 20%; \r\n");
      out.write("\t\t\tmargin-left: 85%;\r\n");
      out.write("\t\t\tmargin-top: 1%;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#div3 a{\r\n");
      out.write("\t\t\tposition: static;\t\t\t\r\n");
      out.write("\t\t\tcursor: pointer;\r\n");
      out.write("\t\t\tcolor: black;\r\n");
      out.write("\t\t\tfont-size: 20px;\r\n");
      out.write("\t\t\ttext-decoration: none;\t\r\n");
      out.write("\t\t\ttext-align:center;\r\n");
      out.write("\t\t\tcolor: white;\t\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#div3 a:hover {\r\n");
      out.write("\t\t\tbackground-color: white;\t\t\t\r\n");
      out.write("\t\t\tfont-size: 20px;\r\n");
      out.write("\t\t\tcolor: black;\r\n");
      out.write("\t\t\ttext-decoration: none;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t#select{\r\n");
      out.write("\t\t\tmargin-top: 0.5%;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t#mainimg{\r\n");
      out.write("\t\t\tposition: absolute;\r\n");
      out.write("\t\t\tcolor: white;\r\n");
      out.write("\t\t\tmargin-left: 1%;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#div2{\r\n");
      out.write("\t\t\tmargin-left: 15%;\t\t\t\r\n");
      out.write("\t\t\ttop: 1%;\r\n");
      out.write("\t\t\tborder-bottom: solid 1px black;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#div2 a{\r\n");
      out.write("\t\t\tposition: static;\t\t\t\r\n");
      out.write("\t\t\tcursor: pointer;\r\n");
      out.write("\t\t\tcolor: white;\r\n");
      out.write("\t\t\tfont-size: 20px;\r\n");
      out.write("\t\t\ttext-decoration: none;\t\r\n");
      out.write("\t\t\ttext-align:center;\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#div2 a:hover {\r\n");
      out.write("\t\t\tbackground-color: white;\r\n");
      out.write("\t\t\tcolor: black;\t\t\t\r\n");
      out.write("\t\t\tfont-size: 20px;\r\n");
      out.write("\t\t\ttext-decoration: none;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#div2 p{\r\n");
      out.write("\t\t\tmargin-left: 12%;\r\n");
      out.write("\t\t\tposition: absolute;\r\n");
      out.write("\t\t\tmargin-top: -1.5%;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#mainimg{\r\n");
      out.write("\t\t\tcursor: pointer;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tbutton{\r\n");
      out.write("\t\t\tcursor: pointer;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#selbtn{\r\n");
      out.write("\t\t\tborder: 0;\r\n");
      out.write("\t\t\tbackground-color: black;\r\n");
      out.write("\t\t\tcolor: white;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#selbtn:hover {\r\n");
      out.write("\t\t\tbackground-color: white;\r\n");
      out.write("\t\t\tcolor: black;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"overflow-x:hidden; overflow-y:auto;\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"back\" style=\"height: 58;\" > \r\n");
      out.write("\t<!-- img id=\"mainimg\"  src=\"resources/img.jpg\" width=\"200px;\" onclick=\"location.href='./'\"> -->\r\n");
      out.write("\t<h2 id=\"mainimg\" onclick=\"location.href='./'\"> 슈마니커</h2>\r\n");
      out.write("\t\t \r\n");
      out.write("\t\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"div2\" style=\"margin-top: 1%\"> \r\n");
      out.write("\t\t<a href=\"category\">카테고리</a>\r\n");
      out.write("\t\t<a href=\"speller\">맞춤 상품</a>\t\t\t\r\n");
      out.write("\t\t<p><input id=\"select\" type=\"text\"/><button id=\"selbtn\">검색</button></p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("/* \t$(\"#select\").click(function() {\r\n");
      out.write("\t\tif($(\"#selbtn\").css(\"diplay\")==\"none\"){\r\n");
      out.write("\t\t\t$(\"#selbtn\").css(\"diplay\", \"block\");\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$(\"#selbtn\").css(\"diplay\")==\"none\");\r\n");
      out.write("\t\t};\r\n");
      out.write("\t});\r\n");
      out.write("\t */\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"dim-layer\">\r\n");
      out.write("    <div class=\"dimBg\"></div>\r\n");
      out.write("    <div id=\"layer2\" class=\"pop-layer\">\r\n");
      out.write("        <div class=\"pop-container\">\r\n");
      out.write("            <div class=\"pop-conts\">\r\n");
      out.write("                <!--content //-->\r\n");
      out.write("                <h4 class=\"ctxt mb20\">상점 이름을 입력 하세요</h4>\r\n");
      out.write("                   <input id=\"shopname\" type=\"text\">\r\n");
      out.write("\t\t\t\t   <input type =\"button\" value=\"중복확인\" onclick=\"shopOverlay()\"/>\r\n");
      out.write("                </p>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"btn-r\">\r\n");
      out.write("                    <a href=\"#\" class=\"btn-layerClose\">확인</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!--// content-->\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"mymenu\">\r\n");
      out.write("\t\t<a href=\"./myproductCall\">상품등록</a>\r\n");
      out.write("\t\t<a href=\"./mybuyCall\">구매내역</a>\r\n");
      out.write("\t\t<a href=\"./mycartCall\">찜목록</a>\r\n");
      out.write("\t\t<a href=\"./myreview\">상점후기 </a>\r\n");
      out.write("\t\t<a href=\"./myinfo\" id=\"myinfo\">개인정보 수정</a>\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\tif('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.shopState eq 1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'){\r\n");
      out.write("\t\t\tgetShopInfo();\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$('.btn-example').click(function(){\r\n");
      out.write("\t    var $href = $(this).attr('href');\r\n");
      out.write("\t    layer_popup($href);\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction layer_popup(el){\r\n");
      out.write("\r\n");
      out.write("\t    var $el = $(el);        //레이어의 id를 $el 변수에 저장\r\n");
      out.write("\t    var isDim = $el.prev().hasClass('dimBg');   //dimmed 레이어를 감지하기 위한 boolean 변수\r\n");
      out.write("\t\r\n");
      out.write("\t    isDim ? $('.dim-layer').fadeIn() : $el.fadeIn();\r\n");
      out.write("\t\r\n");
      out.write("\t    var $elWidth = ~~($el.outerWidth()),\r\n");
      out.write("\t        $elHeight = ~~($el.outerHeight()),\r\n");
      out.write("\t        docWidth = $(document).width(),\r\n");
      out.write("\t        docHeight = $(document).height();\r\n");
      out.write("\t\r\n");
      out.write("\t    // 화면의 중앙에 레이어를 띄운다.\r\n");
      out.write("\t    if ($elHeight < docHeight || $elWidth < docWidth) {\r\n");
      out.write("\t        $el.css({\r\n");
      out.write("\t            marginTop: -$elHeight /2,\r\n");
      out.write("\t            marginLeft: -$elWidth/2\r\n");
      out.write("\t        })\r\n");
      out.write("\t    } else {\r\n");
      out.write("\t        $el.css({top: 0, left: 0});\r\n");
      out.write("\t    }\r\n");
      out.write("\t\r\n");
      out.write("\t    $el.find('a.btn-layerClose').click(function(){\r\n");
      out.write("\t    \tif($('#shopname').val() != '' && overChk == true){\r\n");
      out.write("\t    \t\tisDim ? $('.dim-layer').fadeOut() : $el.fadeOut(); // 닫기 버튼을 클릭하면 레이어가 닫힌다.\t\r\n");
      out.write("\t    \t}\t        \r\n");
      out.write("\t        return false;\r\n");
      out.write("\t    });\r\n");
      out.write("\t\r\n");
      out.write("\t    $('.layer .dimBg').click(function(){\r\n");
      out.write("\t        $('.dim-layer').fadeOut();\r\n");
      out.write("\t        return false;\r\n");
      out.write("\t    });\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\t//상점이름 입력 후 확인 클릭시 값 INSERT\r\n");
      out.write("\t$('.btn-layerClose').click(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif($('#shopname').val() == ''){\r\n");
      out.write("\t\t\talert('상점명은 반드시 기입하셔야 합니다. 다시 입력하여 주세요');\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tif (!overChk) {\r\n");
      out.write("\t\t\t\talert(\"상점명 중복 체크를 실행 해 주세요!\");\r\n");
      out.write("\t\t\t\t$('#shopname').focus();//포커스 이동\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse if($('#shopname').val() != ''){\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\ttype:\"GET\",\r\n");
      out.write("\t\t\t\t\turl:\"./setShopName\",\r\n");
      out.write("\t\t\t\t\tdata:{\r\n");
      out.write("\t\t\t\t\t\tshopName : $('#shopname').val() ,\r\n");
      out.write("\t\t\t\t\t\tid : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tdataType:\"JSON\",\r\n");
      out.write("\t\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\t\tif(data.success>0){\r\n");
      out.write("\t\t\t\t\t\t\tconsole.log('insert 성공');\r\n");
      out.write("\t\t\t\t\t\t\tupShopState();\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror : function(err){\r\n");
      out.write("\t\t\t\t\t\tconsole.log(err);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}); \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tvar overChk = false;//중복체크 값\r\n");
      out.write("\t//상점명 중복 확인\r\n");
      out.write("\tfunction shopOverlay(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"GET\",\r\n");
      out.write("\t\t\turl:\"./shopOverlay\",\r\n");
      out.write("\t\t\tdata:{\r\n");
      out.write("\t\t\t\tshopName : $('#shopname').val()\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdataType:\"JSON\",\r\n");
      out.write("\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\tif(data.overlay){\r\n");
      out.write("\t\t\t\t\talert('이미 사용중인 상점명입니다. 다른 상점명을 입력해 주세요');\r\n");
      out.write("\t\t\t\t\t$('#shopname').val('');\r\n");
      out.write("\t\t\t\t\t$('#shopname').focus();\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\talert(\"사용 가능한 상점명 입니다.\");\r\n");
      out.write("\t\t\t\t\t$('#shopname').css('color', 'green');\r\n");
      out.write("\t\t\t\t\toverChk = true;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(err){\r\n");
      out.write("\t\t\t\tconsole.log(err);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//상점개설 여부 상태값 UPDATE\r\n");
      out.write("\tfunction upShopState(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"GET\",\r\n");
      out.write("\t\t\turl:\"./upShopState\",\r\n");
      out.write("\t\t\tdata:{\r\n");
      out.write("\t\t\t\tidx : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdataType:\"JSON\",\r\n");
      out.write("\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\tif(data.success > 0){\r\n");
      out.write("\t\t\t\t\tconsole.log('상태값 수정완료');\r\n");
      out.write("\t\t\t\t\tgetMemShopState();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(err){\r\n");
      out.write("\t\t\t\tconsole.log(err);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}); \r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//상점개설상태 값 얻기\r\n");
      out.write("\tfunction getMemShopState(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"GET\",\r\n");
      out.write("\t\t\turl:\"./getMemShopState\",\r\n");
      out.write("\t\t\tdata:{\r\n");
      out.write("\t\t\t\tid : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdataType:\"JSON\",\r\n");
      out.write("\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\tif(data.result != null){\r\n");
      out.write("\t\t\t\t\tconsole.log(data.result);\r\n");
      out.write("\t\t\t\t\tconsole.log('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.shopState}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("');\r\n");
      out.write("\t\t\t\t\talert('상점이 개설되었습니다.');\r\n");
      out.write("\t\t\t\t\tlocation.href = \"./mypage?id='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(err){\r\n");
      out.write("\t\t\t\tconsole.log(err);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//상점정보 출력\r\n");
      out.write("\tfunction getShopInfo(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"GET\",\r\n");
      out.write("\t\t\turl:\"./getShopInfo\",\r\n");
      out.write("\t\t\tdata:{\r\n");
      out.write("\t\t\t\tid : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdataType:\"JSON\",\r\n");
      out.write("\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\tif(data.dto != null){\r\n");
      out.write("\t\t\t\t\t$('#shopInfo').append(\r\n");
      out.write("\t\t\t\t\t\"<h3>상점 이름 =\" + data.dto.shop_name + \"<br/>\" +\r\n");
      out.write("\t\t\t\t\t\"상품판매 개수 = \" + data.dto.shop_sellcount + \"<br/>\" +\r\n");
      out.write("\t\t\t\t\t\"상점 개설 날짜 = \" + data.dto.shop_date + \"<br/> </h3>\" +\r\n");
      out.write("\t\t\t\t\t\"<h3>상점 주인=<div id='mem_id'>\"+data.dto.mem_id+\"</div></h3>\"\r\n");
      out.write("\t\t\t\t\t);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(err){\r\n");
      out.write("\t\t\t\tconsole.log(err);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t/* var openWin;\r\n");
      out.write("\t$(\"#myinfo\")\r\n");
      out.write("\t\t\t.click(\r\n");
      out.write("\t\t\t\t\tfunction() {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t// window.name = \"부모창 이름\"; \r\n");
      out.write("\t\t\t\t\t\twindow.name = \"parentForm\";\r\n");
      out.write("\t\t\t\t\t\t//window.open(\"open할 window\", \"자식창 이름\", \"팝업창 옵션\");\r\n");
      out.write("\t\t\t\t\t\topenWin = window\r\n");
      out.write("\t\t\t\t\t\t\t\t.open(\"./myinfo\", \"childForm\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"width=800, height=800, resizable = no, scrollbars = no, left = 300, top= 200\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t}); */\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   <h3>상점후기 내역</h3>\r\n");
      out.write("   <button id=\"reviewWrite\">글등록 </button>\r\n");
      out.write("   \r\n");
      out.write("   <div id=\"rev1\">\r\n");
      out.write("      후기  <input type=\"text\" id=\"sreply_content\"/> \r\n");
      out.write("      평점  <select id=\"starRate\">\r\n");
      out.write("            <option selected=\"selected\">5</option>\r\n");
      out.write("            <option>4</option>\r\n");
      out.write("            <option>3</option>\r\n");
      out.write("            <option>2</option>\r\n");
      out.write("            <option>1</option>\r\n");
      out.write("         </select>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("   <div id=tab>\r\n");
      out.write("      <table>\r\n");
      out.write("         <thead>\r\n");
      out.write("            <tr>\r\n");
      out.write("               <th>구매자</th>\r\n");
      out.write("               <th>후기내용</th>\r\n");
      out.write("               <th>날짜</th>\r\n");
      out.write("               <th>평점</th>\r\n");
      out.write("               <th></th>\r\n");
      out.write("            </tr>\r\n");
      out.write("         </thead>\r\n");
      out.write("         <tbody id=\"myReview\">\r\n");
      out.write("         </tbody>\r\n");
      out.write("      </table>      \r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("         var obj = {};//초기화   \r\n");
      out.write("         obj.type = \"post\";\r\n");
      out.write("         obj.dataType = \"json\";\r\n");
      out.write("         obj.enctype = \"multipart/form-data\";\r\n");
      out.write("         obj.data={};\r\n");
      out.write("         obj.error = function(e) {\r\n");
      out.write("            console.log(e)\r\n");
      out.write("         };\r\n");
      out.write("         $(document).ready(function() {\r\n");
      out.write("            listPrint();\r\n");
      out.write("         });\r\n");
      out.write("         //후기 리스트 출력\r\n");
      out.write("         function listPrint() {\r\n");
      out.write("            \r\n");
      out.write("            obj.url = \"./reviewList\";\r\n");
      out.write("            obj.data = {};\r\n");
      out.write("            obj.data.shop_idx = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.shopIdx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("            obj.success = function(data) {\r\n");
      out.write("               console.log(data);\r\n");
      out.write("               var content = \"\";\r\n");
      out.write("               var totalscore = 0;\r\n");
      out.write("               var reviewcnt =0;\r\n");
      out.write("               var avgRate = 0\r\n");
      out.write("               data.reviewList.forEach(function(item, index) {\r\n");
      out.write("                    content += \"<tr>\";\r\n");
      out.write("                      content += \"<td id='reviewWriter'>\"+item.mem_id+\"</td>\";\r\n");
      out.write("                      content += \"<td><input id ='reviewcontent'  type =text class=\"+item.sreply_idx+\" value=\"+item.sreply_content+\" readonly/></td>\";\r\n");
      out.write("                      var date = new Date(item.sreply_date);\r\n");
      out.write("                      content +=\"<td>\"+date.toLocaleDateString(\"ko-KR\")+\"</td>\";\r\n");
      out.write("                      content +=\"<td>\"\r\n");
      out.write("                               +\"<span class='star-input'>\"\r\n");
      out.write("                              +\"<span class='input'>\"\r\n");
      out.write("                               +\"<input type='radio' name=\"+item.sreply_idx+\" id=\"+item.sreply_star+\" checked>\"\r\n");
      out.write("                               +\"<label for=\"+item.sreply_star+\">\"+item.sreply_star+\"</label>\"\r\n");
      out.write("                               +\"</span>\"\r\n");
      out.write("                               +\" <select id='starRateup' >\"\r\n");
      out.write("                                 +\"<option selected='selected'>5</option>\"\r\n");
      out.write("                                +\"<option>4</option>\"\r\n");
      out.write("                                +\"<option>3</option>\"\r\n");
      out.write("                                +\"<option>2</option>\"\r\n");
      out.write("                                +\"<option>1</option>\"\r\n");
      out.write("                          +\"</select>\"\r\n");
      out.write("                                +\"<output id='out' for='star-input'><b>\"+item.sreply_star+\"</b>점</output>\"   \r\n");
      out.write("                              +\"</span>\"\r\n");
      out.write("                              +\"</td>\";\r\n");
      out.write("                           totalscore += item.sreply_star;\r\n");
      out.write("                           reviewcnt += 1;\r\n");
      out.write("                           \r\n");
      out.write("                      if(item.mem_id=='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'){\r\n");
      out.write("                         content += \"<td><input id=\"+item.sreply_idx+\" type=button class='reviewdel' value='삭제'/></td>\"\r\n");
      out.write("                         content += \"<td ><input id=\"+item.sreply_idx+\" name=update\"+item.sreply_idx+\" type=button class='reviewupdate'  value='완료'/>\"\r\n");
      out.write("                                        +\"<input id=\"+item.sreply_idx+\" name=form\"+item.sreply_idx+\" type=button class='reviewupdateform'  value='수정'/>\"\r\n");
      out.write("                                           + \"</td>\";\r\n");
      out.write("\r\n");
      out.write("                         \r\n");
      out.write("                         content += \"</tr>\";\r\n");
      out.write("                      }else{\r\n");
      out.write("                         content += \"</tr>\";\r\n");
      out.write("                      }\r\n");
      out.write("                      console.log(totalscore/reviewcnt);\r\n");
      out.write("                      avgRate=totalscore/reviewcnt;\r\n");
      out.write("                  });\r\n");
      out.write("\r\n");
      out.write("            $(\"#myReview\").empty();\r\n");
      out.write("            $(\"#myReview\").append(content);\r\n");
      out.write("            $(\"#avgRate\").empty();\r\n");
      out.write("            $(\"#avgRate\").append(avgRate);\r\n");
      out.write("            }            \r\n");
      out.write("               \r\n");
      out.write("                ajaxCall(obj); \r\n");
      out.write("            }\r\n");
      out.write("               //후기 작성\r\n");
      out.write("             $(\"#reviewWrite\").click(function() {\r\n");
      out.write("                if($(\"#sreply_content\").val()==\"\"){\r\n");
      out.write("                  alert(\"댓글 내용을 입력해주세요\");\r\n");
      out.write("               }\r\n");
      out.write("               else{\r\n");
      out.write("                  obj.url = \"./reviewWrite\";\r\n");
      out.write("                     obj.data = {};\r\n");
      out.write("                     obj.data.shop_idx = $(\"#shop_idx\").text();\r\n");
      out.write("                     obj.data.mem_id = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("                     obj.data.sreply_content = $(\"#sreply_content\").val();\r\n");
      out.write("                     obj.data.sreply_star=$(\"#starRate option:selected\").val();\r\n");
      out.write("                     console.log($(\"#shop_idx\").text()+\"/\"+obj.data.mem_id+\"/\"+$(\"#sreply_content\").val());\r\n");
      out.write("                     obj.success = function(data) {\r\n");
      out.write("                        if (data.success > 0) {\r\n");
      out.write("                           alert(\"댓글쓰기에 성공 했습니다.\");\r\n");
      out.write("                           listPrint();\r\n");
      out.write("                           } else {\r\n");
      out.write("                           alert(\"댓글쓰기에 실패 했습니다.\");\r\n");
      out.write("                        }\r\n");
      out.write("                     }\r\n");
      out.write("                  }\r\n");
      out.write("                  ajaxCall(obj); \r\n");
      out.write("               }); \r\n");
      out.write("            /*후기  삭제 */\r\n");
      out.write("            $(document).on('click','.reviewdel', function() {\r\n");
      out.write("               $.ajax({\r\n");
      out.write("                  type : \"post\",\r\n");
      out.write("                  url : \"./reviewdel\",\r\n");
      out.write("                  data : {\r\n");
      out.write("                     delreply : $(this).attr('id')\r\n");
      out.write("                  },\r\n");
      out.write("                  dataType : \"json\",\r\n");
      out.write("                  success : function(data) {//인자 값은 서버에서 주는 메세지\r\n");
      out.write("                     if (data.success) {\r\n");
      out.write("                        //listPrint(data.list)\r\n");
      out.write("                        alert(\"삭제 성공\")\r\n");
      out.write("                        location.reload();\r\n");
      out.write("                     } else {\r\n");
      out.write("                        alert(\"삭제 실패\")\r\n");
      out.write("                     }\r\n");
      out.write("                  }\r\n");
      out.write("               });\r\n");
      out.write("               ajaxCall(obj);\r\n");
      out.write("            });\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            //후기 수정\r\n");
      out.write("              $(document).on('click', '.reviewupdateform', function() {   \r\n");
      out.write("                var upcomment = $(this).attr(\"id\");\r\n");
      out.write("                console.log(upcomment);\r\n");
      out.write("                $(\"input[class=\" + upcomment + \"]\").css(\"border\",\"1px solid #004C63\");\r\n");
      out.write("                $(\"input[class=\" + upcomment + \"]\").attr(\"readonly\",false);\r\n");
      out.write("                $(\".input\").css(\"display\",\"none\");\r\n");
      out.write("                $(\"#starRateup\").css(\"display\",\"inline\");\r\n");
      out.write("                $(\"#out\").css(\"display\",\"none\")\r\n");
      out.write("                \r\n");
      out.write("                 $(\"input[name= form\"+upcomment+\"]\").css(\"display\",\"none\");\r\n");
      out.write("              $(\"input[name= update\"+upcomment+\"]\").css(\"display\",\"inline\"); \r\n");
      out.write("\r\n");
      out.write("              \r\n");
      out.write("              \r\n");
      out.write("            $(document).on('click', '.reviewupdate', function() {\r\n");
      out.write("               console.log(\"수정\");\r\n");
      out.write("                  var sreply_idx = $(this).attr('id');\r\n");
      out.write("                \r\n");
      out.write("                  var reviewcontent = $(\"input[class=\"+sreply_idx+\"]\").val();\r\n");
      out.write("                  //var time=$(\"inpput[class=\" +upcomment+\"]\").id;\r\n");
      out.write("                  //var content= $(\".edit\").val();   \r\n");
      out.write("\r\n");
      out.write("                  obj.url = \"./reviewupdate\";\r\n");
      out.write("                  obj.data = {};\r\n");
      out.write("                  obj.data.sreply_idx = sreply_idx;\r\n");
      out.write("                  obj.data.reviewcontent = reviewcontent;\r\n");
      out.write("                  obj.data.sreply_star=$(\"#starRateup option:selected\").val();\r\n");
      out.write("                  console.log(obj.data.sreply_idx+\"/\"+obj.data.reviewcontent);\r\n");
      out.write("                  obj.success = function(data) {\r\n");
      out.write("                     console.log(data);\r\n");
      out.write("                     if (data.success) {\r\n");
      out.write("                        alert(\"수정에 성공하였습니다.\")\r\n");
      out.write("                        location.reload();\r\n");
      out.write("                     } else {\r\n");
      out.write("                        alert(\"수정 실패\")\r\n");
      out.write("                     }\r\n");
      out.write("\r\n");
      out.write("                  };\r\n");
      out.write("\r\n");
      out.write("                  ajaxCall(obj);\r\n");
      out.write("               \r\n");
      out.write("               });\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("               function ajaxCall(param) {\r\n");
      out.write("                   console.log(param);\r\n");
      out.write("                   $.ajax(param);\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/././head.jsp(124,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginId == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t<div id=\"div3\">\t\t\r\n");
          out.write("\t\t<a href=\"./joinForm\">회원가입</a>\r\n");
          out.write("\t\t<a href=\"./index\">로그인</a>\r\n");
          out.write("\t\t<a href=\"#\">공지사항</a><br/>\r\n");
          out.write("\t</div>\t\r\n");
          out.write("\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/././head.jsp(132,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginId != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t<div id=\"div1\">\t\t\r\n");
          out.write("\t\t<a href=\"./logout\">로그아웃</a>\r\n");
          out.write("\t\t<a href=\"./mypage?id='");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("'\">마이페이지</a>\r\n");
          out.write("\t\t<a href=\"#\">공지사항</a>\r\n");
          out.write("\t\t<a href=\"#\">요청게시판</a>\r\n");
          out.write("\t\t<a href=\"#\">찜목록</a><br/>\r\n");
          out.write("\t</div>\t\r\n");
          out.write("\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/././head.jsp(142,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginId == 'admin'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t<div id=\"div1\">\t\t\r\n");
          out.write("\t\t<a href=\"adminpage\">관리자 페이지</a>\r\n");
          out.write("\t\t<a href=\"#\">로그아웃</a>\r\n");
          out.write("\t\t<a href=\"#\">마이페이지</a>\r\n");
          out.write("\t\t<a href=\"#\">공지사항</a>\r\n");
          out.write("\t\t<a href=\"#\">요청게시판</a>\r\n");
          out.write("\t\t<a href=\"#\">찜목록</a><br/>\r\n");
          out.write("\t</div>\t\r\n");
          out.write("\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /WEB-INF/views/./mypage.jsp(130,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.shopState eq 0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t<div id=\"myname\">\r\n");
          out.write("\t\t\t<h2 align=\"center\">상점이 없습니다. 상점을 개설 하여 주세요</h2>\r\n");
          out.write("\t\t\t<h4 align=\"center\"><a href=\"#layer2\" class=\"btn-example\">상점개설</a></h4>\r\n");
          out.write("\t\t</div>\r\n");
          out.write("\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent(null);
      // /WEB-INF/views/./mypage.jsp(137,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.shopState eq 1 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t<div id=\"shopInfo\"></div>\r\n");
          out.write("\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }
}
