/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.30
 * Generated at: 2018-07-18 02:59:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class regProduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/FinalProjecthee/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/final/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1531184863091L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("        \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("   <script src=\"http://code.jquery.com/jquery-3.1.0.min.js\"></script>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("   #proInfo{\r\n");
      out.write("      width: 150%;\r\n");
      out.write("      height: 50%;\r\n");
      out.write("      margin-left: 60%;\r\n");
      out.write("      margin-top: -13%;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   #mainimg2{\r\n");
      out.write("      width: 97%;\r\n");
      out.write("      height: 105%;\r\n");
      out.write("      border: 1px solid black;\r\n");
      out.write("      margin-left: 1%;\r\n");
      out.write("      margin-top: 2%;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   #mainimg2:hover{\r\n");
      out.write("      cursor:pointer;\r\n");
      out.write("      background-color: #EAEAEA;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   #mainParent{\r\n");
      out.write("    margin-left: 20%;\r\n");
      out.write("    width: 37%;\r\n");
      out.write("    height: 200px;   \r\n");
      out.write("    margin-top: 7%;\r\n");
      out.write("}\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   #subParent{\r\n");
      out.write("      width: 40%;\r\n");
      out.write("      height: 300px;      \r\n");
      out.write("      margin-left: 30%;\r\n");
      out.write("      margin-top: 1%;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   #subImg{\r\n");
      out.write("         position: absolute;\r\n");
      out.write("       width: 36%;\r\n");
      out.write("       height: 30%;\r\n");
      out.write("       margin-left: -0.4%;\r\n");
      out.write("       margin-top: 2%;\r\n");
      out.write("       border: 1px solid black;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   #proname{\r\n");
      out.write("      margin-left: 1.65%;\r\n");
      out.write("   }\r\n");
      out.write("   #price{\r\n");
      out.write("      margin-left: 1%;\r\n");
      out.write("   }\r\n");
      out.write("   #size{\r\n");
      out.write("      margin-left: 1.65%;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   #brand{\r\n");
      out.write("      margin-left: 1.7%;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   #gender{\r\n");
      out.write("      margin-left: 2.4%;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   #category{\r\n");
      out.write("      margin-left: 2.4%;\r\n");
      out.write("   }\r\n");
      out.write("  \r\n");
      out.write("   #memo{\r\n");
      out.write("         margin-left: 60%;\r\n");
      out.write("           margin-top: -1%;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   #register{\r\n");
      out.write("    margin-top: 1%;\r\n");
      out.write("    margin-left: 73%;\r\n");
      out.write("    background-color: black;\r\n");
      out.write("    color: white;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    border: 0;\r\n");
      out.write("   }   \r\n");
      out.write("   #register:hover{\r\n");
      out.write("       background-color: white;\r\n");
      out.write("       color: black;\r\n");
      out.write("   } \r\n");
      out.write("   #mainUpBtn{                \r\n");
      out.write("       position: absolute;\r\n");
      out.write("       margin-top: 1.88%;\r\n");
      out.write("       margin-left: -24.2%;\r\n");
      out.write("       width: 35.5%;\r\n");
      out.write("       height: 26.4%;\r\n");
      out.write("       background-color: white;\r\n");
      out.write("       border:0;\r\n");
      out.write("       cursor: pointer;\r\n");
      out.write("       font-size: 40px;\r\n");
      out.write("       border: 0;\r\n");
      out.write("   }\r\n");
      out.write("   #mainUpBtn:hover {\r\n");
      out.write("      background-color: black;\r\n");
      out.write("      color: white;\r\n");
      out.write("   } \r\n");
      out.write("   #proText{\r\n");
      out.write("      margin-top: 4%;\r\n");
      out.write("      height: 234px;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./head.jsp", out, false);
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   <div id=\"mainParent\" align=\"center\">\r\n");
      out.write("           <font size=\"2\">메인이미지를 업로드 하세요 (*필수!)</font>\r\n");
      out.write("      <input id=\"mainUpBtn\" type=\"button\" onclick=\"mainUpload()\" value=\"+\"/>\r\n");
      out.write("         <div id=\"mainimg2\" contenteditable=\"false\"></div>\r\n");
      out.write("   </div>\r\n");
      out.write("  \r\n");
      out.write("   <div id=\"proInfo\">\r\n");
      out.write("      상품명<input id=\"proname\" type=\"text\"/><br/><br/>\r\n");
      out.write("     \r\n");
      out.write("      판매가격<input id=\"price\" type=\"text\"/><br/><br/>\r\n");
      out.write("           \r\n");
      out.write("     브랜드<select id=\"brand\">\r\n");
      out.write("               <option value=\"0\">종류를 선택해주세요</option>\r\n");
      out.write("               <option value=\"1\">NIKE</option>\r\n");
      out.write("               <option value=\"2\">ADIDAS</option>\r\n");
      out.write("               <option value=\"3\">FILA</option>\r\n");
      out.write("               </select><br/><br/>\r\n");
      out.write("     \r\n");
      out.write("      성별<select id=\"gender\">\r\n");
      out.write("               <option value=\"0\">성별을 선택해주세요</option>\r\n");
      out.write("               <option value=\"1\">남자</option>\r\n");
      out.write("               <option value=\"2\">여자</option>\r\n");
      out.write("               </select><br/><br/> \r\n");
      out.write("               \r\n");
      out.write("      종류<select id=\"category\">\r\n");
      out.write("               <option value=\"0\">종류를 선택해주세요</option>\r\n");
      out.write("               <option value=\"1\">운동화</option>\r\n");
      out.write("               <option value=\"2\">구두</option>\r\n");
      out.write("               <option value=\"3\">샌들</option>\r\n");
      out.write("               <option value=\"4\">단화</option>\r\n");
      out.write("               </select><br/><br/>                   \r\n");
      out.write("               \r\n");
      out.write("      사이즈<select id=\"size\">\r\n");
      out.write("               <option value=\"0\">신발 사이즈를 선택하세요</option>\r\n");
      out.write("               <option>210mm</option>\r\n");
      out.write("               <option>215mm</option>\r\n");
      out.write("               <option>220mm</option>\r\n");
      out.write("               <option>225mm</option>\r\n");
      out.write("               <option>230mm</option>\r\n");
      out.write("               <option>235mm</option>\r\n");
      out.write("               <option>240mm</option>\r\n");
      out.write("               <option>245mm</option>\r\n");
      out.write("               <option>250mm</option>\r\n");
      out.write("               <option>255mm</option>\r\n");
      out.write("               <option>260mm</option>\r\n");
      out.write("               <option>265mm</option>\r\n");
      out.write("               <option>270mm</option>\r\n");
      out.write("               <option>275mm</option>\r\n");
      out.write("               <option>280mm</option>\r\n");
      out.write("               <option>285mm</option>\r\n");
      out.write("               <option>290mm</option>\r\n");
      out.write("               <option>295mm</option>\r\n");
      out.write("               <option>300mm</option>\r\n");
      out.write("         </select><br/><br/>        \r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("    <div id =\"subParent\" style=\"margin-left: 21%\">\r\n");
      out.write("          서브이미지를 업로드 하세요<br/>(선택사항이며 3장까지 가능합니다)\r\n");
      out.write("        <input id=\"subUpBtn\" type=\"button\" onclick=\"subUpload()\" value=\"업로드\"/>\r\n");
      out.write("            <div id=\"subImg\" contenteditable=\"false\"><input id=\"subImgForm\" type=\"hidden\" name=\"subContent\"/></div>\r\n");
      out.write("   </div>\r\n");
      out.write("    \r\n");
      out.write("    <div id=\"memo\">\r\n");
      out.write("          상품설명<br/><textarea id=\"proText\" rows=\"10\" cols=\"60\"></textarea>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <input type=\"button\" id=\"register\" value=\"등록\">\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("   // div의 html/텍스트 변경 감지\r\n");
      out.write("   $(\"body\").on('DOMSubtreeModified', \"#mainimg2\", function() {\r\n");
      out.write("       $('#mainUpBtn').css('display', 'none');\r\n");
      out.write("       $('#mainimg2').css('border', '0px');\r\n");
      out.write("       $('#mainParent').css('border', '0px');\r\n");
      out.write("   });\r\n");
      out.write("\r\n");
      out.write("   $('#register').click(function(e){   \r\n");
      out.write("      var mainText = $('#mainimg2').html(); //메인이미지에 사진이 올라갔는지 판별하기 위한 변수\r\n");
      out.write("         if(mainText.indexOf('<img') == -1){\r\n");
      out.write("            alert('메인이미지는 반드시 넣어주셔야 합니다.');\r\n");
      out.write("            console.log($('#mainimg2').html());\r\n");
      out.write("         }\r\n");
      out.write("         else if($('#proname').val() == ''){\r\n");
      out.write("            alert('상품명을 입력하여 주세요');\r\n");
      out.write("            $('#proname').focus();\r\n");
      out.write("         }else if($('#price').val() == ''){\r\n");
      out.write("            alert('가격을 입력하여 주세요');\r\n");
      out.write("            $('#price').focus();\r\n");
      out.write("         }else if($('#brand').val() == 0){\r\n");
      out.write("            alert('브랜드를 선택하여 주세요');\r\n");
      out.write("            $('#brand').focus();\r\n");
      out.write("         }else if($('#gender').val() == 0){\r\n");
      out.write("            alert('성별을 선택하여 주세요');\r\n");
      out.write("            $('#gender').focus();\r\n");
      out.write("         }else if($('#category').val() == 0){\r\n");
      out.write("            alert('카테고리를 선택하여 주세요');\r\n");
      out.write("            $('#category').focus();\r\n");
      out.write("         }else if($('#size').val() == 0){\r\n");
      out.write("            alert('사이즈를 선택하여 주세요');\r\n");
      out.write("            $('#size').focus();\r\n");
      out.write("         }else if($('#proText').val() == ''){\r\n");
      out.write("            alert('메모를 작성하여 주세요');\r\n");
      out.write("            $('#proText').focus();\r\n");
      out.write("         }else{\r\n");
      out.write("            $.ajax({\r\n");
      out.write("               type:\"GET\",\r\n");
      out.write("               url:\"./proInsert\",\r\n");
      out.write("               data:{\r\n");
      out.write("                  pro_name: $('#proname').val(),\r\n");
      out.write("                  pro_price: $('#price').val(),\r\n");
      out.write("                  brand_idx: $('#brand').val(),\r\n");
      out.write("                  gender_idx: $('#gender').val(),\r\n");
      out.write("                  shoes_idx: $('#category').val(),\r\n");
      out.write("                  pro_size: $('#size option:selected').text(),\r\n");
      out.write("                  pro_memo:$('#proText').val(),\r\n");
      out.write("                  shop_idx: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.shopIdx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("',\r\n");
      out.write("                  mem_id:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'         \r\n");
      out.write("               },\r\n");
      out.write("               dataType:\"JSON\",\r\n");
      out.write("               success:function(data){\r\n");
      out.write("                    console.log(data);\r\n");
      out.write("                      alert('정상적인 등록 처리가 되었습니다.');\r\n");
      out.write("                      if($('#subImg').html() == ''){\r\n");
      out.write("                         location.href = \"./detail?idx=\" + data.proIdx; \r\n");
      out.write("                      }else{\r\n");
      out.write("                         addSubImg(data.proIdx); //서브이미지 넣을시 추가해주는 함수\r\n");
      out.write("                         location.href = \"./detail?idx=\" + data.proIdx; \r\n");
      out.write("                      }\r\n");
      out.write("               },\r\n");
      out.write("               error : function(err){\r\n");
      out.write("                  console.log(err);\r\n");
      out.write("               }\r\n");
      out.write("            });  \r\n");
      out.write("         }   \r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("   //메인 DIV 클릭시 파일업로드 이벤트 실행\r\n");
      out.write("   function mainUpload(){\r\n");
      out.write("      //fileUpload 새창을 띄운다.\r\n");
      out.write("       var myWin =  window.open(\"./mainUploadForm\",\"파일 업로드\",\"width=400, height=100\");\r\n");
      out.write("       if('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.pathSession ne null}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'){fileDel();}\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   //서브 이미지 업로드\r\n");
      out.write("   function subUpload(){\r\n");
      out.write("      var myWin = window.open(\"./subUploadForm\", \"파일 업로드\", \"width=400, height=100\");\r\n");
      out.write("          if($('#subImg').html().match(/subDel/g).length > 2){ // 업로드파일이 3개면 업로드버튼 숨기기\r\n");
      out.write("             alert('업로드는 3개 까지만 가능합니다.');\r\n");
      out.write("             myWin.close();\r\n");
      out.write("            $('#subUpBtn').attr(\"disabled\", true);\r\n");
      out.write("            console.log($('#subImg').html());\r\n");
      out.write("      } \r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   //메인사진 삭제\r\n");
      out.write("   function mainDel(elem){\r\n");
      out.write("      var fileName = elem.id.split(\"/\")[2];\r\n");
      out.write("      console.log(fileName);\r\n");
      out.write("      $.ajax({\r\n");
      out.write("         url:\"./mainFileDel\",\r\n");
      out.write("         type:\"get\",\r\n");
      out.write("         data:{\"fileName\":fileName},\r\n");
      out.write("         dataType:\"JSON\",\r\n");
      out.write("         success:function(data){\r\n");
      out.write("            if(data.success == 1){\r\n");
      out.write("               $(elem).prev().remove();//이미지 삭제\r\n");
      out.write("               $(elem).remove();//버튼 삭제\r\n");
      out.write("               $('#mainUpBtn').css('display', 'inline'); // 삭제버튼 클릭하면 다시 업로드버튼 나오게하기\r\n");
      out.write("               $('#mainimg2').css('border', '1px solid black');\r\n");
      out.write("            }\r\n");
      out.write("         },\r\n");
      out.write("         error:function(e){\r\n");
      out.write("            console.log(e);\r\n");
      out.write("         }\r\n");
      out.write("      });\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   //서브사진 삭제\r\n");
      out.write("   function subDel(elem){\r\n");
      out.write("        var fileName = elem.id.split(\"/\")[2];\r\n");
      out.write("      console.log(fileName);\r\n");
      out.write("      test(elem);\r\n");
      out.write("      $.ajax({\r\n");
      out.write("         url:\"./subFileDel\",\r\n");
      out.write("         type:\"get\",\r\n");
      out.write("         data:{\"fileName\":fileName},\r\n");
      out.write("         dataType:\"JSON\",\r\n");
      out.write("         success:function(data){\r\n");
      out.write("            if(data.success == 1){\r\n");
      out.write("               $(elem).prev().remove();//이미지 삭제\r\n");
      out.write("               $(elem).remove();//버튼 삭제\r\n");
      out.write("               $('#subUpBtn').attr(\"disabled\", false);\r\n");
      out.write("            }\r\n");
      out.write("         },\r\n");
      out.write("         error:function(e){\r\n");
      out.write("            console.log(e);\r\n");
      out.write("         }\r\n");
      out.write("      });\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   //서브이미지 업데이트(서브사진추가)\r\n");
      out.write("   function addSubImg(proIdx){\r\n");
      out.write("       $.ajax({\r\n");
      out.write("         url:'./subImgInsert',\r\n");
      out.write("         type:'get',\r\n");
      out.write("         data:{\r\n");
      out.write("            proIdx : proIdx\r\n");
      out.write("         },\r\n");
      out.write("         dataType:\"JSON\",\r\n");
      out.write("         success:function(data){\r\n");
      out.write("            console.log(data);\r\n");
      out.write("         },\r\n");
      out.write("         error:function(err){\r\n");
      out.write("            console.log(err);\r\n");
      out.write("         }\r\n");
      out.write("      }); \r\n");
      out.write("   }\r\n");
      out.write("   //메인이미지세션 관리\r\n");
      out.write("   function fileDel(){\r\n");
      out.write("      $.ajax({\r\n");
      out.write("         url:\"./fileDel\",\r\n");
      out.write("         type:\"get\",\r\n");
      out.write("         data:{\"fileName\":'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.pathSession}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'},\r\n");
      out.write("         dataType:\"JSON\",\r\n");
      out.write("         success:function(data){\r\n");
      out.write("            if(data.success == 1){\r\n");
      out.write("            }\r\n");
      out.write("         },\r\n");
      out.write("         error:function(e){\r\n");
      out.write("            console.log(e);\r\n");
      out.write("         }\r\n");
      out.write("      });\r\n");
      out.write("   }\r\n");
      out.write("  \r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
